### PR TITLE
Updates the research summary on the credential settings page.

### PR DESCRIPTION
**Pull request by lamawmouk**
This change updates the research summary description on the credentialing application page to encourage users to provide more context about the data they want to use and for what purposes the data will be used for e.g. research or commercial etc.

### CODE REVIEW

**Comment by tompollard** [comment]
Thanks Lama, (assuming you agree!) please could you tweak the message to:

`Please provide a detailed description of how you plan to use the data, including the name of any specific dataset(s) you intend to use. If you will be using the data for a class, please also include the name and number of the course.`

**Comment by tompollard** [comment]
@lamawmouk another quick thought. We should probably increase the allowed word length for this section, because otherwise people will struggle to give any kind of detail (I think you mentioned that the limit is 150 characters?).

**Comment by lamawmouk** [comment]
The limit is 150 words (1000 characters).

**Comment by tompollard** [comment]
> The limit is 150 words (1000 characters).

Got it, so okay for now?

**Comment by lamawmouk** [comment]
I think we should add a minimum word limit and raise an error if less than say  100 words?

**Comment by tompollard** [comment]
> I think we should add a minimum word limit

This may need a bit of discussion with the team. Might be best to save for later to avoid holding up this PR!

**Comment by tompollard** [comment]
Thanks Lama, looks good to me!

**Pull request merged**
