### PR TITLE
CITISOAPSERVICE configuration

### PR DESCRIPTION
**Pull request by lamawmouk**
As discussed with @bemoody and given the CITI API workflow in #1937, this PR will create the configuration to set up the credentials of the CITI SOAP SERVICE on the PhysioNet platform.

### CODE REVIEW

**Comment by bemoody** [comment]
Please add more explanation in `.env.example`.

The comment in .env.example should say something about *what* this username/password are used for and *why*.

The comment should also say something about how to obtain such credentials (link to public documentation from CITI if possible).

Most importantly, the comment should explain how to change or revoke the credentials in case of a security breach.

All of the secrets that are currently stored in .env *should* be changed regularly.  (None of them currently *are* being changed regularly AFAIK, which is a problem.  But at a bare minimum we need to document the process for doing so.)

**Comment by bemoody** [comment]
Also, leave these values blank in .env.example so that the feature is not enabled by default in devlelopment configurations.

**Comment by lamawmouk** [comment]
Thank you @bemoody! I have updated the changes.

**Comment by alistairewj** [comment]
Merged in #1964

**Pull request closed without merging**
