### PR TITLE
Quota 1

### PR DESCRIPTION
**Pull request by elfeto**
Adding a fixed disk quota in the projects managed by the system.

In the sudoers file, the user `pn` or `ALL`, depending on what you want, has to be enabled to run the set quota command
`
ALL     ALL=(ALL) NOPASSWD:/usr/local/bin/set-quota.sh
`

There are 4 times the quota should be touched. 
1. On project create
2. On active project publish
3. On project quota increase request
4. On version create
     - On version publish

**The quotas at the moment are cumulative, so all versions would share the same quota.** 
There is a new file `set-quota.sh` that should be placed in `/usr/local/bin/`, and the execution of that would alter the disk quota.

This should be tested a bit more, and the input inn the bash script can be checked before running also.
#518

### CODE REVIEW

**Comment by elfeto** [comment]
Note, I forgot to mention that for the projects in the demo, I added the initial quota for one project.

**Comment by bemoody** [comment]
Thanks for working on this.  It's a good start.

The set-quota.sh script has a number of issues - it doesn't validate
its inputs at all.  It's quite difficult to do this sort of thing
safely in a shell script; why not rewrite it in Python (or Perl)?

I think we may not actually need named groups at all (just assign
numeric GIDs from a large reserved range) and if we could avoid that
it would simplify things quite a bit.  xfs_quota command appears to
accept numeric IDs, at least.

Some smaller things:
 - you can just use 'auto_now', instead of 'auto_now_add' and updating
the timestamp by hand
 - use subprocess.check_call (or similar) instead of os.system
 - 'settings.QUOTA' is unclear, maybe call it 'settings.USE_FILESYSTEM_QUOTA' ?

All of this should be better documented as well, with comments
explaining why things are being done this way.

**Comment by bemoody** [comment]
> I think we may not actually need named groups at all (just assign
> numeric GIDs from a large reserved range) and if we could avoid that
> it would simplify things quite a bit.  xfs_quota command appears to
> accept numeric IDs, at least.

We probably should keep track of all GIDs that have been assigned,
even if the project is later deleted; but my thought is that this info
can be kept in the relational database and probably doesn't need to be
pushed out to the system group database as well.  What do you think?

**Comment by elfeto** [comment]
Just in case, the changes done have to be tested now in my VM, but I have to push them here first to then pull in the VM.

**Comment by elfeto** [comment]
I will close this for now, but leave the branch open for future references. It will still need some work after all the PRs.

**Pull request closed without merging**
