### PR TITLE
Increase maximum character length for affiliations 

### PR DESCRIPTION
**Pull request by lamawmouk**
This PR addresses the issue #1129. The problem arises when a project is published, and an error is raised if a user includes an affiliation of over 150 characters while being the contact author.

In this pull request, I have modified the codebase to increase the maximum character length for affiliations in the `Contact` class model. This update ensures that longer affiliations can be accommodated without triggering any errors.

Please review and merge the change at your convenience.

### CODE REVIEW

**Comment by tompollard** [comment]
Thanks for looking at this Lama.

Increasing the length to 300 characters is definitely an improvement. It doesn't solve the underlying issue though (that three affiliations, each of 150 characters, get combined into a single field). 

Instead of bumping to 300 characters, how about following Benjamin's suggestion below by removing the length constraint?

> Perhaps the Contact fields simply shouldn't have maximum lengths at all. 

This should prevent us getting more errors when publishing projects. We can then think about improving the validation on the fields later.

**Comment by bemoody** [comment]
> Instead of bumping to 300 characters, how about following Benjamin's suggestion below by removing the length constraint?

This would mean either:

- changing the `models.CharField` to a `models.TextField` and removing `max_length`

- keeping `CharField` and setting `max_length=None` (supported since Django 4.2, if I understand correctly?) which potentially has portability issues

I think I would slightly prefer having an explicit limit (MAX_AFFILIATIONS * (MAX_AFFILIATION_LENGTH + 2)) but removing the limit should also work.

**Comment by tompollard** [comment]
> I think I would slightly prefer having an explicit limit (MAX_AFFILIATIONS * (MAX_AFFILIATION_LENGTH + 2)) but removing the limit should also work.

This also sounds fine to me!

**Comment by tompollard** [comment]
Thanks Lama, looks good! Before we merge, please could you:

- Remove the trailing whitespace in physionet-django/project/forms.py (line 670)
- Squash the commits? (perhaps one commit with the code change, and one commit for the migration)

**Comment by lamawmouk** [comment]
Thank you Benjamin and Tom! I have added the changes.

**Comment by tompollard** [comment]
Looks great, thanks @lamawmouk.

I see the migration was generated using an older version of Django (`# Generated by Django 3.1.14 on 2023-07-11 20:51`). Not an issue here, but we're now using Django 4 so you might want to update it at some point.

**Pull request merged**
