### PR TITLE
Ensure internal notes are displayed to editors.

### PR DESCRIPTION
**Pull request by tompollard**
In https://github.com/MIT-LCP/physionet-build/pull/2255 we added a feature to store "internal notes" for projects. There is a bug in the current implementation that means notes are not displayed to people "editing" a project (see: https://github.com/MIT-LCP/physionet-build/issues/2262). This fixes that bug.

To reproduce the bug:

- Login as `tompollard`
- Go to http://localhost:8000/console/submitted-projects/p7TCIMkltNswuOB9FZH1/info/ and add an internal note
- Go to http://localhost:8000/console/submitted-projects/p7TCIMkltNswuOB9FZH1/edit/. No note!

### CODE REVIEW

**Comment by tompollard** [comment]
Side note, the implementation of the /info/ and /edit/ pages is very muddled. I added a comment about this in the docstrings of the relevant views. We should refactor at some point.

**Comment by bemoody** [comment]
That's just one of many.  awaiting_authors.html, copyedit_submission.html, edit_submission.html, publish_submission.html, submission_info.html all include submission_info_card.html.

Notice all the common stuff (ReassignEditorForm, EmbargoFilesDaysForm, ...) that is getting passed to render() in every one of those view functions.

We should at the very least factor out that stuff into one function, e.g.:
```
def submission_info_card_params(request, project):
    return {
        # template parameters used by submission_info_card.html
        'project': project,
        'authors': authors,
        'author_emails': author_emails,
        'storage_info': storage_info,
        ...
        'reassign_editor_form': reassign_editor_form,
        'embargo_form': embargo_form,
        'notes': notes,
        'internal_note_form': internal_note_form,
    }

def edit_submission(request):
    ...
    return render(request, {
        **submission_info_card_params(project),
        # any additional template parameters used by edit_submission.html
        ...
    }
```

(It looks like that was the original intent of `project.info_card`, but that function wasn't designed in an extensible way.)

**Comment by tompollard** [comment]
Thanks for your suggestion Benjamin. I updated the templates that I missed, and added a `submission_info_card_params` function in an attempt to start consolidating some of the common function calls. More refactoring/cleaning needed, but if possible I'd like to save this for a new PR.

**Comment by bemoody** [comment]
Looks good, thanks!

**Pull request merged**
