### PR TITLE
Updated the Project Access Page to display the policy descriptions conditionally.

### PR DESCRIPTION
**Pull request by Rutvikrj26**
This PR addresses the confusion created on HDN due to different between the policy documentation listed and the policy choices available. This makes the description for each policy conditional to the access policy being allowed.

### CODE REVIEW

**Comment by Rutvikrj26** [comment]
@tompollard This is the smaller PR that solves the issue of project access copy.

**Comment by bemoody** [comment]
Thanks!  One small issue.  In project/views.py:
```
from physionet.settings.base import ALLOWED_ACCESS_POLICIES
```

We don't want to import from physionet.settings.base.  Instead, use
```
        'access_policy_choices': settings.ALLOWED_ACCESS_POLICIES,
```

**Review by tompollard — CHANGES_REQUESTED** [review]
Thanks, looks fine to me. 

In future, it is helpful if you provide a more detailed comment, outlining things to look out for in the change. e.g. in this case a new description of "Contributor Review" was introduced.

Couple of minor things before we merge:

1. Please add the missing newline to the end of access_policies.html

2. Please modify the following text:

`<li><strong>Contributor Review</strong>: Only {{ SITE_NAME }} credentials who sign a DUA and submit a project plan approved by the data holder may access the files.</li>`

to:

`<li><strong>Contributor Review</strong>: Only {{ SITE_NAME }} credentialed users who sign a DUA and submit a project plan approved by the data contributor may access the files.</li>`

**Comment by Rutvikrj26** [comment]
Thanks @tompollard & @bemoody 

I found out that "Contributor Review" part has been missing after I had drafted the PR and hence missed. 
I'll make sure to add any new additions/removals in the PR Description.

**Review by tompollard — APPROVED** [review]

**Comment by tompollard** [comment]
Thanks Rutvik!

**Pull request merged**
