### PR TITLE
Allow handling editor to be reassigned

### PR DESCRIPTION
**Pull request by elfeto**
Allow the current project editor to reassign the project. This will send an email to both the new and old editor.

The form changes are handled in the submission_info function only.

Closing #943

### CODE REVIEW

**Comment by tompollard** [comment]
Thanks Felipe, this will be very useful. I haven't had a chance to review the code, but it works well from a user perspective. I've added a couple of quick thoughts below:

- Could you add an extra administrator to the fixtures to make this easy to test?
- Are there any simple tests that you could add to the testing framework?
- It looks like changes aren't logged. Will this be in a separate PR/issue?

**Comment by elfeto** [comment]
> - Could you add an extra administrator to the fixtures to make this easy to test?

I added in the fixture another administrator
> - Are there any simple tests that you could add to the testing framework?

I added the test to the console tests
> - It looks like changes aren't logged. Will this be in a separate PR/issue?

I added a log message

**Comment by tompollard** [comment]
Looks good to me. I'm happy to merge. @bemoody okay with you? A couple of minor things, indirectly related to this PR, that could be dealt with independently:

- It would be good to have a line break before "Regards" in the email sent to editors:

Screen Shot 2020-04-01 at 16 30 29

- On the project submission timeline (e.g. http://localhost:8000/projects/P4HIXQ3yZtNV11JoaUQw/submission/), I think we should remove the editor's name and email address (which solves the issue that the page displays the current editor, rather than the editor at the time it was assigned).

Screen Shot 2020-04-01 at 16 19 24

**Comment by elfeto** [comment]
> On the project submission timeline (e.g. http://localhost:8000/projects/P4HIXQ3yZtNV11JoaUQw/submission/), I think we should remove the editor's name and email address (which solves the issue that the page displays the current editor, rather than the editor at the time it was assigned).

I can replace the text saying an editor has been assign, removing the name and email, but that will be overwritten (the date) if the editor is reassigned. (its just how its written)

**Comment by elfeto** [comment]
@bemoody  can you take a look at this and the problems @tompollard mentions of the submission timeline.
>On the project submission timeline (e.g. http://localhost:8000/projects/P4HIXQ3yZtNV11JoaUQw/submission/), I think we should remove the editor's name and email address (which solves the issue that the page displays the current editor, rather than the editor at the time it was assigned).

The problem there is that there is that the editor is part of the "SubmissionInfo" which only allows one person and once its re-assign the `editor` and `editor_assignment_datetime` changes.

This will show omit the first editor and editor assignment date from the timeline. 

I believe @tompollard  also wants to remove the editor information from the timeline, but even by replacing it for `An editor has been assign to your submission` or the text you want to add, the dates will change if the project is re-assigned. 

This could be replaced with a new model of project logging. Assuming we log into a model all actions done in a project like:
 - Creation
 - Submission
 - Editor assignment and reassignment
 - Author asked to do changes
 - Copyedit changes / no changes
 - Author approval / Who approves
 - Publish

I might have missed one or 2, but that can be added in the proper code / PR.

The same could be done to users... to track changes in an easy way to find.

**Comment by tompollard** [comment]
Thanks @elfeto, overall I think this is an improvement and I'd be happy to merge. 

As you mention, the issue that we create is this: currently we know who was responsible for all editorial decisions (acceptance, copyediting, publishing) because it is implicit, but when we implement the change we only know the current editor. 

I'm good with making a separate PR to introduce fixes to capture the changing state, but I'd like @bemoody to confirm that he is also happy.

**Comment by bemoody** [comment]
Yeah, this is ugly.  I agree the EditLogs and CopyeditLogs and
hardcoded timestamps and such are not ideal.

Probably the easiest way for now would be:
- don't show the editor's name/address in the timeline
- don't change the editor_assignment_datetime when re-assigning

but it would certainly be good to think about having a more flexible
system for logging events in the timeline.

**Comment by tompollard** [comment]
Thanks @bemoody. @elfeto, please could you make the suggested changes?

> - don't show the editor's name/address in the timeline
> - don't change the editor_assignment_datetime when re-assigning

Once these are done, let's merge and then try to address the state issue in a new PR.

**Comment by elfeto** [comment]
There is no field in any models that mark a re-assignment.
> - don't change the editor_assignment_datetime when re-assigning

Would not be possible. This is a show or don't show scenario. 
Unless we add a field to the model `project_reassignment` as bool.

**Comment by elfeto** [comment]
NVM on my comment, I didndt read the `don't change`. I read don't show :D

**Comment by bemoody** [comment]
Is the idea that only the current editor is able to reassign the
project?  That doesn't appear to be enforced.

I think it would be clearer to add a new function "reassign_editor"
rather than adding arguments to "assign_editor".  Or else make the
behavior implicit: you update submission_status and
editor_assign_datetime *only if* submission_status is currently less
than 20.

What is this about?

+{% if project.editor == user %}
+<script>
+  function set_editor_text(){
+    $('#project_author').text($( "#id_editor option:selected" ).text());
+  }
+</script>
+{% endif %}

What does the project author have to do with anything?

**Comment by elfeto** [comment]
>I think it would be clearer to add a new function "reassign_editor"
rather than adding arguments to "assign_editor".  Or else make the
behavior implicit: you update submission_status and
editor_assign_datetime *only if* submission_status is currently less
than 20.

The submission status is 10 at that point. This function before this PR was used only once and it was to alter the change of the submission status while assigning the editor.

**Comment by tompollard** [comment]
Thanks everyone, I think the core issues are now addressed. Nice work @elfeto. @bemoody good spot on `project_author` and I agree that handling the reassignment in a new function looks cleaner!

**Pull request merged**
