### PR TITLE
Background tasks 2

### PR DESCRIPTION
**Pull request by elfeto**
Added a proper name to the action in background tasks.
In the admin page we have now:
   - GCP - \<Project name> 
   - Read Only Files - \<Project name> (This was missing from PR #554)

Adressed #568

### CODE REVIEW

**Comment by bemoody** [comment]
Please fix your doc strings.

What does it mean that 'physionet' is added to INSTALLED_APPS?
Why are you doing that here?

I would recommend writing:

 ('foo - %s' % project)

or if you prefer,

 ('foo - {}'.format(project))

rather than

 ('foo - ' + str(project))

**Comment by elfeto** [comment]
Done :)

**Comment by bemoody** [comment]
What's the significance of the changes in project/admin.py?

**Comment by elfeto** [comment]
By default all "INSTALLED_APPS" in the settings/base.py file will be automatically registered to the admin page. What I am doing in the project/admin.py is to unregister those installed applications in particular the "Completed tasks" and "tasks", and I copy pasted the Package page, and removed the "task_name" that was the name of the function (the same for all), and replaced it with the verbose_name that can be edited to what we want. Then after doing the custom admin module, I added it to the admin page.

**Comment by bemoody** [comment]
Sounds good :)

**Pull request merged**
