### PR TITLE
Reorganizes models in the events app.

### PR DESCRIPTION
**Pull request by danamouk**
As referenced in #1782, this pull request organizes the models code in the events app. As part of the transition of the models from the users app to the events app, two migrations for both the user and events app are created. In the `user/model.py` to avoid fields.E304 Reverse accessor clashes in Django, old related names were added as part of foreign key and in the `events/model.py` User in the foreign key was modified to "user.User".

Other aspects that are reorganizated as part of the events app include `events/enums.py` and `events/validators.py`, `events/admin.py`.

### CODE REVIEW

**Comment by bemoody** [comment]
(I haven't fully reviewed this code yet.)

As discussed with Dana and Tom, this pull request will delete any existing event/participant information (stored in `user_event` and `user_eventparticipant` tables) and create new tables from scratch.  We haven't yet used the event system on PhysioNet except for internal testing, and it's simpler to delete and re-create the models than to move old data over.

**Comment by bemoody** [comment]
To fix the error `*** FAILED: Testing old server (after early migrations)`, you also need to add `MIGRATE_AFTER_INSTALL = True` to `user/migrations/0049_auto_20230112_1430.py`.

The error `*** FAILED: Checking migrations were undone` is a bug in `test-upgrade.sh` that will happen any time a new app is added.

**Comment by tompollard** [comment]
> We haven't yet used the event system on PhysioNet except for internal testing, and it's simpler to delete and re-create the models than to move old data over.

Deleting all current data is good with me!

**Comment by tompollard** [comment]
@danamouk thanks! please could you rebase this branch on the latest version of the dev branch?

**Comment by danamouk** [comment]
thanks @tompollard and @bemoody, rebased to `dev` on `reorg_models` and got message to confirm no conflicts, "Successfully rebased and updated refs/heads/reorg_models."

**Comment by tompollard** [comment]
Thanks Dana, looks good to me. Going to merge this so I can sign up for the "What is a Health Widget?" course!

**Pull request merged**
