### PR TITLE
No downloading stuff in compilestatic

### PR DESCRIPTION
**Pull request by bemoody**
No, you may not download files from physionet.org as part of the compilestatic command.  That is madness.

### CODE REVIEW

**Comment by tompollard** [comment]
Is it bad enough to require undoing? Isn't the only risk that you do something stupid with your .env file, or is it worse than that?  @amitupreti, perhaps you could modify the approach to only allow local files to be added?

**Comment by bemoody** [comment]
I'm sorry for not explaining.

Downloading stuff as part of the installation is not a good idea.  The installation process needs to be reproducible - installing the server twice with the same code must produce the same results.  Additionally for offline development and for a lot of testing, it's important to be able to run the server without external network access.  So no downloads!

(This particular case is especially bizarre because you've literally made that URL a prerequisite for itself.  We need to be able to set up a physionet server *when physionet.org is inaccessible*.)

There are countless ways of making the stylesheets locally customizable; I don't really care how that is done.  But you can't overwrite files tracked in the git repository and you can't require network access during installation.

**Comment by tompollard** [comment]
Thanks Benjamin. 

> The installation process needs to be reproducible - installing the server twice with the same code must produce the same results. 

Hmm, I'd assumed that the .env file also supported local paths, but now I see this isn't the case (e.g. `BACKGROUND_IMAGE='./physionet-build/physionet-django/static
/images/background.jpg'`) fails with an `unknown url` error. Again, should have checked the PR more carefully. Hopefully @amitupreti can provide an option for local images files.

**Comment by tompollard** [comment]
@amitupreti Okay if I merge this PR for now and we add back the custom image later? Will this cause any issues for Health Data Nexus?

**Comment by alistairewj** [comment]
@amitupreti is off today but feel free to merge, it's nothing we can't manage.

**Comment by superryeti** [comment]
> s it bad enough to require undoing? Isn't the only risk that you do something stupid with your .env file, or is it worse than that? @amitupreti, perhaps you could modify the approach to only allow local files to be added?

For sure, i remember initially i had added the option for local or download, but i removed the local option for some reason i dont remember(stupid)
Let me open another pr that lets us use local files.

Regarding merging, it should be fine as we haven't deployed changes to the HDN, so HDN should be good.

**Pull request merged**
