### PR TITLE
Minor changes to the wording on the credentialing pages 

### PR DESCRIPTION
**Pull request by lamawmouk**
I wanted to make some minor changes to the code base. This pull request makes two small changes to the languages used on the credentialing pages:

- changing the "Application information" to title case for consistency with the other headers.
- changing the "Process application" to "Process" in the table header to reduce the width of the column.

### CODE REVIEW

**Comment by tompollard** [comment]
@lamawmouk I'm not sure if it was intentional, but it looks like you had unassigned @danamouk. I have just reassigned this to her for review.

**Comment by lamawmouk** [comment]
Hi Tom,

Oops, not sure what happened- I believe she had already reviewed it.

Thanks,
Lama

**Comment by tompollard** [comment]
@lamawmouk there is nothing here to show that the pull request was reviewed. @danamouk give me a shout if i can help with this.

**Comment by danamouk** [comment]
thanks, this looks good to me.

**Review by Lucas-Mc — APPROVED** [review]
Looks good!

**Comment by tompollard** [comment]
thanks everyone! @danamouk please merge if you are happy

**Pull request merged**
