### PR TITLE
Move DOI registration step out of decision form. Refactor utility functions. Add relationships.

### PR DESCRIPTION
**Pull request by tompollard**
This set of changes builds on Felipe's work on integrating PhysioNet with the DataCite API. My initial motivation was to move the DOI registration step later in the publication workflow, because we shouldn't be assigning DOIs until we are confident that the project will be published.

The changes are briefly outlined below:

- Instead of an "auto register DOI" option in the editorial decision form, there is a "reserve DOI" tab in `/console/templates/console/submission_info_card.html` that is viewable when a project is ready to publish (`project.submission_status == 60`). 
- Instead of separate `get_full_name()` and `get_full_name_srs()` methods on the project model, we now have get_full_name() with a `reverse` argument (wasn't sure of the meaning of SRS).
- The DOI utility functions have been refactored so that we now have "`generate_doi_payload()`" to generate the payload, `register_doi()` to register draft and findable DOIs, and `update_doi` to update the status of a registered DOI. This helps to avoid some duplication of the payload metadata.
- Relationships between the core DOI and the version DOI are now captured in the metadata. The core project will list versions in the `HasVersion` attribute, and the versions will list the core project in the `IsVersionOf` attribute.
- I cannot work out why "version" isn't captured in the DataCite metadata when it is included in the payload. There are examples of Zenodo metadata that include version, so it is definitely possible. I'll look into this.

#### An example of "draft" DOI metadata is below:

```
{
  "id": "https://doi.org/10.7966/fp69-se96",
  "doi": "10.7966/FP69-SE96",
  "url": "",
  "types": {
    "resourceTypeGeneral": "Dataset"
  },
  "creators": [],
  "titles": [
    {
      "title": "TEST1"
    }
  ],
  "publisher": "PhysioNet-dev",
  "publicationYear": 2020,
  "descriptions": [
    {
      "description": "Test\n",
      "descriptionType": "Abstract"
    }
  ],
  "relatedIdentifiers": [],
  "providerId": "physiont",
  "clientId": "physiont.physiont",
  "agency": "DataCite",
  "state": "draft"
}
```

#### An example of findable DOI metadata for a (latest version) core project is:

```
{
  "id": "https://doi.org/10.7966/26sk-ks61",
  "doi": "10.7966/26SK-KS61",
  "url": "https://localhost:8000//content/demoeicu/",
  "types": {
    "resourceTypeGeneral": "Dataset"
  },
  "creators": [
    {
      "name": "Mark, Roger Greenwood",
      "givenName": "Roger Greenwood",
      "familyName": "Mark"
    }
  ],
  "titles": [
    {
      "title": "Demo eICU Collaborative Research Database"
    }
  ],
  "publisher": "PhysioNet-dev",
  "publicationYear": 2020,
  "descriptions": [
    {
      "description": "The eICU Collaborative Research Database is a large multi-center critical care\ndatabase made available by Philips Healthcare in partnership with the MIT\nLaboratory for Computational Physiology.\n\n",
      "descriptionType": "Abstract"
    }
  ],
  "relatedIdentifiers": [
    {
      "relationType": "HasVersion",
      "relatedIdentifier": "10.13026/G2F309",
      "relatedIdentifierType": "DOI"
    },
    {
      "relationType": "HasVersion",
      "relatedIdentifier": null,
      "relatedIdentifierType": "DOI"
    }
  ],
  "providerId": "physiont",
  "clientId": "physiont.physiont",
  "agency": "DataCite",
  "state": "findable"
}
```

#### An example of findable DOI metadata for a (versioned) project is:

```
{
  "id": "https://doi.org/10.7966/d31d-z235",
  "doi": "10.7966/D31D-Z235",
  "url": "https://localhost:8000/content/demoeicu/2.1.0/",
  "types": {
    "resourceTypeGeneral": "Dataset"
  },
  "creators": [
    {
      "name": "Mark, Roger Greenwood",
      "givenName": "Roger Greenwood",
      "familyName": "Mark"
    }
  ],
  "titles": [
    {
      "title": "Demo eICU Collaborative Research Database"
    }
  ],
  "publisher": "PhysioNet-dev",
  "publicationYear": 2020,
  "descriptions": [
    {
      "description": "The eICU Collaborative Research Database is a large multi-center critical care\ndatabase made available by Philips Healthcare in partnership with the MIT\nLaboratory for Computational Physiology.\n\n",
      "descriptionType": "Abstract"
    }
  ],
  "relatedIdentifiers": [
    {
      "relationType": "IsVersionOf",
      "relatedIdentifier": "10.7966/26sk-ks61",
      "relatedIdentifierType": "DOI"
    }
  ],
  "providerId": "physiont",
  "clientId": "physiont.physiont",
  "agency": "DataCite",
  "state": "findable"
}
```

### CODE REVIEW

**Comment by elfeto** [comment]
Just trying to do a project submission gave me an error

I just did a resetdb with a loaddemo submitting "MIT-BIH Arrhythmia Database"
```
Internal Server Error: /console/submitted-projects/SHuKI1APLrwWCqxSQnSk/publish/

AttributeError at /console/submitted-projects/SHuKI1APLrwWCqxSQnSk/publish/
'int' object has no attribute 'get_bound_field'

Request Method: GET
Request URL: http://localhost:8000/console/submitted-projects/SHuKI1APLrwWCqxSQnSk/publish/

Traceback:

File "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)
File "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/core/handlers/base.py" in _get_response
  115.                 response = self.process_exception_by_middleware(e, request)
File "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/core/handlers/base.py" in _get_response
  113.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  21.                 return view_func(request, *args, **kwargs)
File "/Users/ftorres/Github/physionet-build/physionet-django/console/views.py" in handling_view
  81.             return base_view(request, *args, **kwargs)
File "/Users/ftorres/Github/physionet-build/physionet-django/console/views.py" in publish_submission
  546.                    'url_prefix': url_prefix})
....
```

**Comment by bemoody** [comment]
> Just trying to do a project submission gave me an error
>
> I just did a resetdb with a loaddemo submitting "MIT-BIH Arrhythmia
> Database"
> ```
> Internal Server Error:
> /console/submitted-projects/SHuKI1APLrwWCqxSQnSk/publish/
>
> AttributeError at /console/submitted-projects/SHuKI1APLrwWCqxSQnSk/publish/
> 'int' object has no attribute 'get_bound_field'
>
> Request Method: GET
> Request URL:
> http://localhost:8000/console/submitted-projects/SHuKI1APLrwWCqxSQnSk/publish/
>
> Traceback:
>
> File
> "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/core/handlers/exception.py"
> in inner
>   34.             response = get_response(request)
> File
> "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/core/handlers/base.py"
> in _get_response
>   115.                 response = self.process_exception_by_middleware(e,
> request)
> File
> "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/core/handlers/base.py"
> in _get_response
>   113.                 response = wrapped_callback(request, *callback_args,
> **callback_kwargs)
> File
> "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/contrib/auth/decorators.py"
> in _wrapped_view
>   21.                 return view_func(request, *args, **kwargs)
> File
> "/Users/ftorres/Github/physionet-build/physionet-django/console/views.py" in
> handling_view
>   81.             return base_view(request, *args, **kwargs)
> File
> "/Users/ftorres/Github/physionet-build/physionet-django/console/views.py" in
> publish_submission
>   546.                    'url_prefix': url_prefix})
> ....
> ```

I don't see that - I'm guessing that you didn't fully reset the
database, had some leftover migration files or something?  What
happens at the *end* of the traceback?  That's the interesting part.

**Comment by bemoody** [comment]
1. I think the behavior of the 'register_doi' form field here is
confusing.

- If the project doesn't have a DOI, then 'register_doi' determines
  whether to generate one; that's useful.

- If the project already has a DOI, then 'register_doi' determines
  whether to update and publish it; that's not so useful.

In particular, if the *core project* has a DOI, it ought to be updated
regardless of whether we're also creating a DOI for the new version.
(Possibly it shouldn't even be an option to skip creating a DOI in
that case.)

The 'draft_doi_exists' form field is not doing anything, and I'm not
sure it would be useful for anything.


2. One feature of Felipe's existing code is that if you have
configured DATACITE_PREFIX/USER/PASS, but these settings are
*incorrect*, it will raise an error at the time you "accept" the
project, so you (maybe) have a chance to fix your broken configuration
before you actually publish the project.

If you think it's really important to publish the project and assign
DOIs in a *single form submission*, I would advise splitting it up
similar to how Felipe originally wrote it:

- create draft DOI(s) and save them to the CoreProject/ActiveProject

- call project.publish and notification.publish_notify

- update and publish the DOIs with the final metadata

That way, if the credentials are bad, it fails without publishing the
project.


3. It looks to me like you're not filling in the HasVersion correctly
for the newly-published version (your example above has a
"relatedIdentifier" of null.)  To create two DOIs that are both
pointing to each other, you *have* to make at least three requests to
the API :)

If some project versions have DOIs and some don't, probably the ones
that don't should be excluded from CoreProject's relatedIdentifiers.

**Comment by elfeto** [comment]
```
(env) ftorres:~/Github/physionet-build/physionet-django$git status
On branch doi2
Your branch is up to date with 'origin/doi2'.

nothing to commit, working tree clean
(env) ftorres:~/Github/physionet-build/physionet-django$git fetch
(env) ftorres:~/Github/physionet-build/physionet-django$git pull
Already up to date.
(env) ftorres:~/Github/physionet-build/physionet-django$./manage.py resetdb && ./manage.py loaddemo
Removed all media files and targeted static files.
Operations to perform:
  Apply all migrations: admin, auth, background_task, contenttypes, notification, project, sessions, sites, user
Running migrations:
  Applying user.0001_initial... OK
  Applying contenttypes.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
...
...
  Applying user.0016_cloudinformation... OK
  Applying user.0017_auto_20190725_1448... OK
  Applying user.0018_legacycredential_reference_email... OK
  Applying user.0019_auto_20190827_1454... OK
  Applying user.0019_auto_20190826_1648... OK
  Applying user.0020_merge_20190827_1605... OK
  Applying user.0021_auto_20190927_1340... OK
  Applying user.0022_auto_20191008_0851... OK
  Applying user.0023_auto_20191125_1500... OK
Installed 29 object(s) from 1 fixture(s)
Installed 4 object(s) from 1 fixture(s)
Installed 4 object(s) from 1 fixture(s)
Installed 88 object(s) from 3 fixture(s)
Copied demo media and static files.
(env) ftorres:~/Github/physionet-build/physionet-django$./manage.py test -v3
System check identified no issues (0 silenced).
test_approve_publish (console.test_views.TestState) ... ok
test_assign_editor (console.test_views.TestState) ... ok
test_copyedit (console.test_views.TestState) ... ok
test_edit (console.test_views.TestState) ... ok
test_edit_reject (console.test_views.TestState) ... ok
test_publish (console.test_views.TestState) ... /Users/ftorres/Github/physionet-build/physionet-django/console/forms.py:233: UserWarning: To register DOIs, add DATACITE credentials to your
                .env file
  .env file""")
ERROR
test_publish_with_doi (console.test_views.TestState) ... ok
test_home (lightwave.tests.TestPublished) ... ok
test_server (lightwave.tests.TestPublished) ... skipped 'sandboxed-lightwave is not installed'
test_home (lightwave.tests.TestUnpublished) ... ok
test_server (lightwave.tests.TestUnpublished) ... skipped 'sandboxed-lightwave is not installed'
test_project_access (project.test_views.TestAccessPresubmission) ... ok
test_project_authors (project.test_views.TestAccessPresubmission) ... ok
test_project_files (project.test_views.TestAccessPresubmission) ... ok
test_visit_get (project.test_views.TestAccessPresubmission) ... ok
test_credentialed (project.test_views.TestAccessPublished) ... ok
test_nonexistent (project.test_views.TestAccessPublished) ... ok
test_open (project.test_views.TestAccessPublished) ... ok
test_invite_author (project.test_views.TestInteraction) ... ok
test_storage_request (project.test_views.TestInteraction) ... ok
test_archive (project.test_views.TestState) ... ok
test_create_archive (project.test_views.TestState) ... ok
test_submit (project.test_views.TestState) ... ok
test_submittable (project.test_views.TestState) ... ok
test_associated_email_choice_form (user.test_forms.TestForms) ... ok
test_associated_email_form (user.test_forms.TestForms) ... ok
test_login_form (user.test_forms.TestForms) ... ok
test_profile_form (user.test_forms.TestForms) ... ok
test_user_creation_form (user.test_forms.TestForms) ... ok
test_edit_password (user.test_integration.TestAuth) ... ok
test_edit_profile (user.test_integration.TestAuth) ... ok
test_logout (user.test_integration.TestAuth) ... ok
test_profile_fixtures (user.test_integration.TestAuth) ... ok
test_user_settings (user.test_integration.TestAuth) ... ok
test_new_email_credential (user.test_integration.TestCredentialing) ... ok
test_registration_credential (user.test_integration.TestCredentialing) ... ok
test_admin_home (user.test_integration.TestPublic) ... ok
test_login (user.test_integration.TestPublic) ... ok
test_reset_password (user.test_integration.TestPublic) ... ok
test_edit_emails (user.test_views.TestAuth) ... ok
test_edit_password_complete (user.test_views.TestAuth) ... ok
test_edit_profile (user.test_views.TestAuth) ... ok
test_user_settings (user.test_views.TestAuth) ... ok
test_public_profile (user.test_views.TestPublic) ... ok
test_register_activate (user.test_views.TestPublic) ... ok

======================================================================
ERROR: test_publish (console.test_views.TestState)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ftorres/Github/physionet-build/physionet-django/console/test_views.py", line 205, in test_publish
    data={'slug':taken_slug, 'register_doi': doi, 'make_zip':1})
  File "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/test/client.py", line 543, in post
    response = super().post(path, data=data, content_type=content_type, secure=secure, **extra)
  File "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/test/client.py", line 357, in post
    secure=secure, **extra)
  File "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/test/client.py", line 422, in generic
    return self.request(**r)
  File "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/test/client.py", line 503, in request
    raise exc_value
  File "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/ftorres/Github/physionet-build/physionet-django/console/views.py", line 81, in handling_view
    return base_view(request, *args, **kwargs)
  File "/Users/ftorres/Github/physionet-build/physionet-django/console/views.py", line 495, in publish_submission
    if project.is_publishable() and publish_form.is_valid():
  File "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/forms/forms.py", line 185, in is_valid
    return self.is_bound and not self.errors
  File "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/forms/forms.py", line 180, in errors
    self.full_clean()
  File "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/forms/forms.py", line 381, in full_clean
    self._clean_fields()
  File "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/forms/forms.py", line 390, in _clean_fields
    if field.disabled:
AttributeError: 'int' object has no attribute 'disabled'

----------------------------------------------------------------------
Ran 45 tests in 21.299s

FAILED (errors=1, skipped=2)
```

I then did the same and stopped just before I did the test and had the same outcome.

Did you got to the page to assign a slug and was able to publish the project via the web browser?

**Comment by bemoody** [comment]
Right, never mind, I was looking at the wrong server :P

**Comment by tompollard** [comment]
Thanks for looking. Best to wait until it's working properly before spending any more time on this! Tests were passing and everything was fine, so I assume I messed something up when I was cleaning the commit history last night. Not had a chance to look at the error yet.

**Comment by tompollard** [comment]
I'm closing this and will make the changes in a new PR.

**Pull request closed without merging**
