### PR TITLE
Add ethics section to submission workflow

### PR DESCRIPTION
**Pull request by fiedosiukr**
This PR creates Ethics section that allows authors to upload additional documents. The available document types are stored in the database. The uploaded documents are stored inside the media directory (protected one) and only the project authors the editor are allowed to access the files. The documents are not available after the publication of the project, but they are copied when a new project version is created.

image

### CODE REVIEW

**Comment by tompollard** [comment]
Thanks @fiedosiukr this looks good. I think it's almost ready to merge, but there are some issues that I came across that it would be good to resolve first. It's a lot of comments, but I hope most of the points are fairly minor:

## 1. Current projects will need to be manually fixed (no action needed)

### 1.1. Populate ethics field for current projects

Projects that are already in the submission system (i.e. projects submitted prior to the upgrade) cannot be published because they do not have the required ethics statement.

The project preview displays the following error:

```
The following errors must be addressed before submission:
Missing required field: Ethics Statement
```

*No fix needed. I can deal with this manually when the changes are pushed to the server.*

## 2. Updates to the submission form (http://localhost:8000/projects/SLUG/ethics/)

### 2.1. Make ethics form multiline

On the submission form (http://localhost:8000/projects/SLUG/ethics/) please could we make the text box multiline (e.g. 5 lines) and perhaps rich text? I think a single line is too small.

Screen Shot 2022-01-14 at 15 50 20


### 2.2. Edit guidance text

On the submission form (http://localhost:8000/projects/SLUG/ethics/) , please could we change "Provide documentation for ethical considerations regarding the resource." 

to: 

"Please provide an ethics statement following the author guidelines (link to /about/publish/#guidelines). Statements on ethics approval should appear here. Your statement will be included in the public project description. "

### 2.3. Edit guidance text

On the submission form (http://localhost:8000/projects/SLUG/ethics/), please could we change: "Upload supporting documents for the resource. See the supporting documents guidance on the for authors page for details." 

to:

"You may upload supporting documents here. These documents will be reviewed by our editorial staff, but they will *not* be shared publicly. For further guidance, please refer to our author guidelines (link to /about/publish/#guidelines)."

### 2.4. Strange behaviour when trying to upload multiple documents

On the submission form (http://localhost:8000/projects/SLUG/ethics/), it does not appear to be possible to upload multiple support documents. 
    a. If I try to upload two of the same kind of document (e.g. two study protocols, I receive the message "Invalid submission. See errors below: " but no error is displayed.
   b. If I try to upload two different types of document (e.g. a study protocol and an ethics approval) strange things happen. e.g. one of the files seems to disappear or the same file appears for both documents.

## 3. Updates to the admin/console pages

### 3.1. Add "No documents were provided." if no documents were uploaded.

In the console, the "Ethics" tab should display a message saying "No documents were provided." or similar under the "Uploaded Documents" header.

Screen Shot 2022-01-14 at 15 40 33

### 3.2.  Allow copyeditor to amend the statement.

In the console, the copyedit form (e.g. http://localhost:8000/console/submitted-projects/SLUG/copyedit/) should allow the editor to edit the ethics section. Ideally the ethics section should appear above "Release Notes" in the form.

Screen Shot 2022-01-14 at 15 47 16

## 4. Add "Ethics" section to the project templates

### 4.1. Update the project templates

The published project and project preview templates should both display the "Ethics" section, preferably above the "Release Notes" section.

Screen Shot 2022-01-14 at 15 48 41

**Comment by tompollard** [comment]
@fiedosiukr looks like there are conflicts with the previous PR :/ Please could you rebase?

Conflicts on: 

```
physionet-django/project/modelcomponents/metadata.py
physionet-django/project/urls.py
physionet-django/project/modelcomponents/publishedproject.py
physionet-django/console/views.py
```

**Comment by fiedosiukr** [comment]
@tompollard done

**Comment by tompollard** [comment]
Looks good to me, thanks @fiedosiukr!

Note that we'll need to: 

- update the About page to provide guidance on how to complete this section.
- load the document types with: 

```python manage.py loaddata ./project/fixtures/site-data.json```

- populate the ethics section for projects under submission, in discussion with the authors.

**Comment by tompollard** [comment]
This is now on the live server. I have:

- updated the About page with a short description of the Ethics section

> Ethics: This section should provide a statement on any ethical issues relevant to the project. This statement will be published with the resource, and typically describes formal approvals acquired for the creation of the resource (such as a review by an ethics board) for users.
Data collected from human subjects: Please provide a statement that the study protocol was approved by relevant Institutional Review Boards (IRBs) or ethics committees. If human participants gave written informed consent, then please state this.
Clinical trial data: Please specify trial registration number and registry name.
Data collected from animals: Please specify the animal care guidelines used in collecting your data. See, for example, this project and this official NIH manual.

- added the two ethics document types from the fixture

We could create a news item too.

**Pull request merged**
