### PR TITLE
Reduce query number.

### PR DESCRIPTION
**Pull request by fiedosiukr**
This PR reduces the database queries amount in some of the admin console views.

### CODE REVIEW

**Comment by tompollard** [comment]
It looks like this changes the information displayed on the user pages. Not necessarily a bad thing, but possibly not intended? Previously the pages aggregated the number of logins, but now each login appears to be listed on a separate row.

e.g.

1. http://localhost:8000/console/users/admin/

Screen Shot 2022-02-10 at 11 26 39

2. http://localhost:8000/console/users/all/

Screen Shot 2022-02-10 at 11 43 02

**Comment by fiedosiukr** [comment]
The number of logins is still aggregated.

1. http://localhost:8000/console/users/all/
image
2. http://localhost:8000/console/users/admin/
image

**Comment by tompollard** [comment]
@fiedosiukr odd, that's not what I saw when testing. I'll take another look!

**Comment by tompollard** [comment]
I was testing in my local environment, rather than Docker, so I assume this is a Postgres vs SQLlite issue. @bemoody Do we care that behaviour is different with SQLlite?

**Pull request merged**
