### PR TITLE
Update Help text for research_summary on Credentialing Application

### PR DESCRIPTION
**Pull request by superryeti**
Currently, during credentialing, we have a minimum limit of 20 words(but this is not obvious to the user as this information is not displayed to user). Users only see the message to provide the details about their research. So when trying to submit credentialing application with less than 20 words, they will keep getting served error by validators(but the error doesnot make it clear about the issue)

As pointed out by January, it will be a good idea if we could show the minimum word limit explicitly.

### CODE REVIEW

**Comment by superryeti** [comment]
Also,  should we make the word limit configurable through the environment variable? @alistairewj @tompollard 
January suggested that we might want to reduce this limit for HDN.

**Comment by tompollard** [comment]
@amitupreti good catch. I think making the length configurable is a good idea!

**Comment by alistairewj** [comment]
yep, another env variable? :)

**Comment by superryeti** [comment]
Okay. I will add that. Thank you

**Comment by tompollard** [comment]
Thanks Amit!

**Pull request merged**
