### PR TITLE
Improve search functionality for projects

### PR DESCRIPTION
**Pull request by superryeti**
**Context**
Related to https://github.com/MIT-LCP/physionet-build/issues/1971

The current search mechanism does
1. Takes the search term from user and breaks it into words
2. Finds projects that has the words on `title`, `abstract` and `description`
3. Calculate relevance score based on how many times the word appear on the above fields of the projects
4. calculate has_keys by checking on which field the words are found for the selected projects, and providing highest preference to the matches found in title
5. Sort results by relevance and has_keys and display to users

This PR implements full text search with Django Postgres for the project model. It adds the same logic as the normal search with Django Postgres full text search,

This PR improves the relevance/results by stemming the search terms which comes with `SearchRank`, which means that it will match different forms of the same word. For example, if someone searches for "ponies", "pony" or "ponying", they will still get results that have the word "pony" in them. This makes the search more flexible and accurate.

However, this PR doesn't do anything about the performance issues  which might happen when the project database gets very large. The documentation says to improve performance we should index the dataset

Indexing: https://docs.djangoproject.com/en/4.1/ref/contrib/postgres/search/#performance

SearchRank: https://docs.djangoproject.com/en/4.1/ref/contrib/postgres/search/#searchrank

### CODE REVIEW

**Comment by bemoody** [comment]
Thanks for looking at this!  So, my thought (not having tried it) is that these changes are likely to be a great improvement, but probably still very limited by the capabilities of Postgres.

I think a better long term strategy would be to use Xapian (or some other package designed for the purpose, though Xapian is the one I'm familiar with.)  It's possible we could implement Xapian-like features using Django and Postgres, but I think it's likely to be a huge amount of work and ultimately less useful.

Of course I'm not allowed to complain because I posted issue #349 four years ago and haven't done anything about it since.  But that would be my gentle suggestion: if you want to spend time on improving the search feature, switching it to a real search engine would be a good start. :)

**Comment by superryeti** [comment]
> Thanks for looking at this! So, my thought (not having tried it) is that these changes are likely to be a great improvement, but probably still very limited by the capabilities of Postgres.
> 
> I think a better long term strategy would be to use Xapian (or some other package designed for the purpose, though Xapian is the one I'm familiar with.) It's possible we could implement Xapian-like features using Django and Postgres, but I think it's likely to be a huge amount of work and ultimately less useful.
> 
> Of course I'm not allowed to complain because I posted issue #349 four years ago and haven't done anything about it since. But that would be my gentle suggestion: if you want to spend time on improving the search feature, switching it to a real search engine would be a good start. :)

Thank you. I will check the Xapian and the old issues

**Comment by tompollard** [comment]
@amitupreti I don't remember if I already posted a link to it, but Django Haystack seems popular: https://django-haystack.readthedocs.io/en/master/index.html and it integrates with "Solr, Elasticsearch, Whoosh, Xapian, etc".

**Comment by tompollard** [comment]
@amitupreti this looks like it is duplicating results in the search. e.g. compare the following URL between the dev branch and the feature branch: http://localhost:8000/content/?topic=eicu

One the dev branch, we see a single result. The screenshot below shows the results on the feature branch:

Screenshot 2023-04-25 at 11 33 44 PM

**Comment by superryeti** [comment]
Thats weird, i dont remember seeing that. let me do some test by creating lots of project and test with that.

Thanks @tompollard

**Comment by superryeti** [comment]
This seems to be coming from  topics__description, Looks like if the publishedproject.topics.all().count() is 3, we will see the published project duplicated 3 times.(for some reason with `related_model` in search, we get duplicate results)
For example
if we search for "eicu" it will appear appears 3 times
if we search for "Demo ECG Signal Toolbox" it will appear 4 times

So far, the solution i found is to 
1. use subquery
2. we cant seem to use distinct because postgres requires us to have the first field in `order_by` to be same  as the field in `distinct`
I am still not sure why it returns duplicate in the first place, i will ask Karol for help.

**Comment by superryeti** [comment]
Thanks @tompollard , i added a subquery to remove the duplicate

related https://forum.djangoproject.com/t/searchquery-and-duplicate-in-queryset/13152

**Comment by tompollard** [comment]
Thanks Amit, looks good to me.

**Comment by tompollard** [comment]
This is definitely an improvement on the previous search. e.g. searching for MIMIC now returns "[MIMIC-III Clinical Database CareVue subset](https://physionet.org/content/mimic3-carevue/1.4/)" and "[MIMIC-IV](https://physionet.org/content/mimiciv/2.2/)" in the top 3 hits.

Previously the top hits for MIMIC were [Chest ImaGenome Dataset](https://physionet.org/content/chest-imagenome/1.0.0/), [Nosocomial Risk Datasets from MIMIC-III](https://physionet.org/content/nosocomialriskdata/1.0/), and [Synthetic Acute Hypotension and Sepsis Datasets Based on MIMIC-III and Published as Part of the Health Gym Project](https://physionet.org/content/synthetic-mimic-iii-health-gym/1.0.0/).

I notice that there are still occasional duplicates being returned, but it is not a huge issue (e.g. take a look at https://physionet.org/content/?topic=eicu). Perhaps better to focus in the new search than worrying about fixing these duplicates

**Pull request merged**
