### PR TITLE
Added outstanding Tasks

### PR DESCRIPTION
**Pull request by elfeto**
Merged all todo tasks into one table outstanding tasks

### CODE REVIEW

**Comment by bemoody** [comment]
Looks pretty good, but what are the different fields for?

AuthorInvitation already has 'request_datetime' (inherited from
BaseInvitation).  'creation_datetime' and 'invitation_datetime' seem
wholly redundant (and neither field is actually used here.)

Then there's 'reply_datetime', which I guess was meant to record when
the author responded to the invitation, but there's already
'response_datetime' for that, and 'reply_datetime' is never used or
set.

Did you mean to add these fields, and what would they be used for?

**Comment by elfeto** [comment]
So the idea under 'invitation_datetime' was to send another invitation X days after, the initial invitation, assuming the person hasn't answered... (but left unfinished...)

Interesting enough, I used 'request_datetime', and not the variables I added, maybe I was going to add them, and then saw that they existed, and forgot to remove them... 

The only one "needed" is 'creation_datetime' of the author object, that is to be able to have some sort of idea, since when one is author, and might be missing the affiliation. 

I'll fix this in the morning :)

**Comment by bemoody** [comment]
Thanks.  I see another issue, though: in project_home.html line
33, you have '{% if invitation_response_formset|length %}'
preceding the table headings, so the headings are not shown if
you have no invitations (but you do have other tasks.)

Please also remove the commented-out cruft in lines 34-36.

This should be formatted as a `<table>` rather than a bag of divs.
But, fine to leave it the way it is for now and fix that in a
later pull request.

**Comment by elfeto** [comment]
Thanks for that catch... This PL closes #295 #327

**Comment by bemoody** [comment]
Made some style fixes.  Okay with you?

**Comment by elfeto** [comment]
Thanks!

**Pull request merged**
