### PR TITLE
Adding integrity error for account registration

### PR DESCRIPTION
**Pull request by elfeto**
Fixing integrity errors on account registrations.

This doesn't fix the issues #761 and #833, but its a start.

I created a template that I believe should be used for ALL integrity errors under the user model, and handle them this way.

I am doing this initial PR to get your opinions.

### CODE REVIEW

**Comment by bemoody** [comment]
I would say that "integrity errors" should not happen.

Or, more specifically: catch *specific* errors that can be triggered
by remote actions (such as trying to create the same username twice.)

We do not want to catch arbitrary errors from the database.  If, let's
say, Django mistakenly tries to assign a primary key that is already
in use, that should raise an error and be logged.

That's just a general statement of principle.  As to how to actually
*implement it*, well...

- we could use get_or_create (appears to have TOCTOU problems, yuck)
  https://docs.djangoproject.com/en/dev/ref/models/querysets/#get-or-create

- we could dig into the exception details (also yuck)

**Comment by elfeto** [comment]
The problem with the "get-or-create" is that since this is a model form with several things being saved at the same time a get or create would be a bit complicated.

**Comment by bemoody** [comment]
What exactly is the problem you're trying to solve here?

The ModelForm *does* check uniqueness, or tries to.  If that is broken
then we should fix it, not paper over it.

**Comment by elfeto** [comment]
There is an integrity error that happens when someone tries to register for an account and double clicks the "Register" button.

Both requests are handled and at the time they are handled there is a check for uniqueness and they are both unique at that point in time. Since one request is executed first, AFTER the uniqueness check, the DB is changed, and then the second request comes and it fails with an IntegrityError.

I cannot think of any other way of fixing this, rather than with a "try: & except IntegrityError:"

**Comment by bemoody** [comment]
The first thing we need is a way to reproduce the issue.  Can you
think of a way to do that in a test case?

ISTM one way to fix it would be to wrap "form.is_valid" + "form.save"
in transaction.atomic.  However, I don't fully understand what that
would do.

* It would presumably mean that if Alice is trying to register an
account, and Bob is also trying to register an account, Bob must wait
for the transaction to finish.

* Would it also mean that if Alice is trying to register an account,
and Bob is trying to change his password, Bob must wait for the
transaction to finish?

* Would it also mean that if Alice is trying to register an account,
and Bob is trying to *log in*, Bob must wait for the transaction to
finish?

**Comment by bemoody** [comment]
Okay, here's another, possibly not so great, idea.

What if we did something like:

    saved = False
    if form.is_valid():
        try:
            form.save()
            saved = True
        except IntegrityError:
            if form.is_valid():
                raise
    if saved:
        # do more stuff
    else:
        # do other stuff

Not so efficient on a per-process level since you might have to run
some checks twice, and lack of locking means it's not completely
foolproof (the person whose name you clashed with might have changed
their name in between the "save" and the second "is_valid") - but it
may be worth it to avoid any locking on these tables.  What do you
think?

If we did something like that, I would suggest it should be wrapped up
into an abstract form class that could be used in multiple places (at
least in user there are many *potential* places for these sorts of
problems to occur.)

**Comment by elfeto** [comment]
To reproduce is quite easy... Just register for an account and double click (fast) the registration button.
For the first one, if we lock the table with the atomic, then for all user related it will have to wait for each registration. All three statements are correct. 

I dislike the second one, it adds a layer of complexity, but might work tho...

What about in the user registration form, the save section do check if an account exists
```

        users_exists = User.objects.filter(Q(username=user.username) |
            Q(email=user.email))

        if not users_exists:
            with transaction.atomic():
                user.save()
                # Save additional fields in Profile model
                profile = Profile.objects.create(user=user,
                    first_names=self.cleaned_data['first_names'],
                    last_name=self.cleaned_data['last_name'])
        else:
            return users_exists.get()
```
That will just send the activation email twice.

**Comment by bemoody** [comment]
Well, I see a couple of practical problems with that:
- since the check doesn't happen within the "atomic", it's still racy
- you're not checking AssociatedEmails

and it seems to me very messy and fragile to have *two* different
places that are supposed to be validating uniqueness, and *two*
different error code paths.

But suppose we did that.  Who would receive the second activation
email, and what would happen to the first one?

- Alice tries to register username 'alice', email address
  'alice@example.com', password 'Tester11!', at the same time Bob
  tries to register username 'bob', email address 'alice@example.com',
  password 'Tester22!'.

- Alice tries to register username 'alice', email address
  'alice@example.com', password 'Tester11!', at the same time Bob
  tries to register username 'alice', email address 'bob@example.com',
  password 'Tester22!'.

In each of these cases, what emails are sent, and what happens if
either or both of the respective activation links are clicked?

**Comment by bemoody** [comment]
test script
----
#!/usr/bin/perl -w

use strict;
use LWP::UserAgent;

my $HOST = 'http://localhost:8000';

my $ua1 = LWP::UserAgent->new;
# $ua1->add_handler("request_send",  sub { shift->dump; return });
# $ua1->add_handler("response_done", sub { shift->dump; return });
$ua1->cookie_jar({});
$_ = $ua1->get("$HOST/register/")->decoded_content;
my ($token1) = /name="csrfmiddlewaretoken" value="([^"]*)"/;

my $ua2 = LWP::UserAgent->new;
$ua2->cookie_jar({});
$_ = $ua2->get("$HOST/register/")->decoded_content;
my ($token2) = /name="csrfmiddlewaretoken" value="([^"]*)"/;

if (fork) {
  $_ = $ua1->post("$HOST/register/",
                  { csrfmiddlewaretoken => $token1,
                    username => 'aaaa',
                    email => 'aaaa@example.com',
                    first_names => 'Aaaa',
                    last_name => 'Aaaa',
                    password1 => 'Tester11!',
                    password2 => 'Tester11!' });
  print $_->status_line, "\n";
}
else {
  $_ = $ua2->post("$HOST/register/",
                  { csrfmiddlewaretoken => $token2,
                    username => 'aaaa',
                    email => 'aaaa@example.com',
                    first_names => 'Aaaa',
                    last_name => 'Aaaa',
                    password1 => 'Tester11!',
                    password2 => 'Tester11!' });
  wait;
  print $_->status_line, "\n";
}
----

**Comment by elfeto** [comment]
Then what about this now. 

I moved the search to inside the atomic transaction.
Now i search for 2 things. If the exact parameters of the registration are being re-submited and if the email already exists....

If the account doesn't exists nor the AssociatedEmail, then create it. 

If the account with the exact same parameters exists, then return it

If the account doesn't exists but the email has been taken, then raise the error?

**Comment by bemoody** [comment]
If I'm reading this right:

(a) If you submit two requests with the same
    username+email+firstname+lastname:

  - very quickly: the second request will send you to a blank
    form with no error message (and the second password will be
    ignored.)

  - not so quickly: the second request will show "User with this
    email already exists" + "A user with that username already
    exists".

(b) If you submit two requests with the same username and different
    email addresses:

  - very quickly: the second request will raise an IntegrityError.

  - not so quickly: the second request will show "A user with
    that username already exists".

(c) If you submit two requests with different usernames and the
    same email address:

  - very quickly: the second request will raise a
    RuntimeError.  (You can't "raise" if you don't have an
    exception to raise.)

  - not so quickly: the second request will show "User with this
    email already exists".


It seems to me that you are trying to do two things at once:
- you're trying to fix a race condition
- you're trying to add special handling for duplicate submissions

Try to figure out how to fix the race condition *without*
changing the existing behavior (i.e. if you submit the same thing
twice in rapid succession, you should see an error just as if you
waited a few seconds.)

*Or* find a way to handle duplicate submissions in a more
friendly way (i.e. if you submit the same thing twice after a few
seconds' delay, show "Thank you for registering" instead of an
error message.)

Don't try to do both of these things at once.


>     saved = False
>     if form.is_valid():
>         try:
>             form.save()
>             saved = True
>         except IntegrityError:
>             if form.is_valid():
>                 raise
>     if saved:
>         # do more stuff
>     else:
>         # do other stuff

In this example, I missed that you also need to call
'form.full_clean()' before calling 'is_valid' the second time.

**Comment by elfeto** [comment]
Here I am going with your approach of the try catch integrity error.

**Comment by elfeto** [comment]
I simplified the commits.
Let me know if this works better or?

**Comment by elfeto** [comment]
Ping to @bemoody  :)

**Comment by bemoody** [comment]
It looks like it should work, but I'm a little confused.  The way this
is written seems more complicated than it needs to be.

Why do you write "if saved or integrity_catch"?  It looks like those
are the only two possibilities - either saved is true and
integrity_catch is false, or saved is false and integrity_catch is
true.  What is the point of this if statement?  What is the point of
having two separate variables in the first place?

Why do you write "if user.is_anonymous and integrity_catch"?  If
integrity_catch is true then user was not assigned in the preceding
block (so you want to instead fetch the conflicting user object.)  The
existing "user" variable must in fact be anonymous, but that's
unrelated.

**Comment by elfeto** [comment]
Now is simpler...
If it's saved, then send the email. If there is an integrity error it means that the user exist, so grab the user to display the proper page.

I removed the variables and unneeded if statements.

**Comment by bemoody** [comment]
Thanks.  I like that this makes the register function shorter and
easier to read.

But now you're catching IntegrityError outside of form.save, which I
think is not a good idea.  If you want to avoid using a variable you
could do "try: / X / except IntegrityError: / Y / else: / Z" although
I'm not a huge fan of that syntax either.

"account_activation_email" is not the best name for that function.
It's a function that Does Something (sends an email); there should be
an imperative verb somewhere in there. :)  The other functions in that
module are... not entirely consistent, but most are either
SOMETHING_notify or notify_SOMETHING.

**Comment by elfeto** [comment]
> "account_activation_email" is not the best name for that function.

Changed.

> But now you're catching IntegrityError outside of form.save, which I
think is not a good idea.  If you want to avoid using a variable you
could do "try: / X / except IntegrityError: / Y / else: / Z" although
I'm not a huge fan of that syntax either.

If I set the try/except inside the save function of the form, then 2 emails will be sent. (if you dont mind, then I can do that. 
```
        try:
            with transaction.atomic():
                user.save()
                # Save additional fields in Profile model
                Profile.objects.create(user=user,
                    first_names=self.cleaned_data['first_names'],
                    last_name=self.cleaned_data['last_name'])
                return user
        except IntegrityError:
            return User.objects.get(username=user.username)
        else:
            raise Exception("Something")
```
If we don't want to send the email 2 times, then the only thing I can think of is the way I did it to set the try/except before the save function is called.
```
            try:
                user = form.save()
                uidb64 = force_text(urlsafe_base64_encode(force_bytes(
                    user.pk)))
                token = default_token_generator.make_token(user)
                notify_account_registration(request, user, uidb64, token)
            except IntegrityError:
                form.full_clean()
                if form.is_valid():
                    raise
                user = User.objects.get(username=form.data['username'])
```
PS. I haven't been able to get the error again. Not sure if this PR is worth it.

**Comment by bemoody** [comment]
> If I set the try/except inside the save function of the form, then 2 emails
> will be sent. (if you dont mind, then I can do that.

I understand.  I think it's better not to send two emails in the
common case where somebody just clicked twice and the form takes a
long time for some reason.

I think you could in fact send the email within RegistrationForm.save
(after the transaction is finished), but I don't like that so much
because then you would be catching IntegrityErrors (if there were any)
that were raised while sending the email, not just IntegrityErrors
raised by the saving of the form data.

Though there's definitely an argument to be made for taking the logic
out of the view functions and into the forms!

> If we don't want to send the email 2 times, then the only thing I can think
> of is the way I did it to set the try/except before the save function is
> called.

You could do it with a temporary variable as you did it in
909763b0f9d68738a0d2bd7ca94fa1822e99f4f1:

try:
    user = form.save()
    saved = True
except IntegrityError:
    form.full_clean()
    if form.is_valid():
        raise
    user = User.objects.get(username=form.data['username'])
    saved = False
if saved:
    uidb64 = force_text(urlsafe_base64_encode(force_bytes(
        user.pk)))
    token = default_token_generator.make_token(user)
    notify_account_registration(request, user, uidb64, token)

Or this would be equivalent, but I think it's less clear:

try:
    user = form.save()
except IntegrityError:
    form.full_clean()
    if form.is_valid():
        raise
    user = User.objects.get(username=form.data['username'])
else:
    uidb64 = force_text(urlsafe_base64_encode(force_bytes(
        user.pk)))
    token = default_token_generator.make_token(user)
    notify_account_registration(request, user, uidb64, token)

**Comment by elfeto** [comment]
What would be the diference in
```
try:
    user = form.save()
except IntegrityError:
    form.full_clean()
    if form.is_valid():
        raise
    user = User.objects.get(username=form.data['username'])
else:
    uidb64 = force_text(urlsafe_base64_encode(force_bytes(
        user.pk)))
    token = default_token_generator.make_token(user)
    notify_account_registration(request, user, uidb64, token)
```
vs 
```
try:
    user = form.save()
    uidb64 = force_text(urlsafe_base64_encode(force_bytes(
        user.pk)))
    token = default_token_generator.make_token(user)
    notify_account_registration(request, user, uidb64, token)
except IntegrityError:
    form.full_clean()
    if form.is_valid():
        raise
    user = User.objects.get(username=form.data['username'])
```
Once the save is done, if there is an integrity error, it till occur before/after the email is sent. (I think)

**Comment by bemoody** [comment]
The difference is that if force_bytes or urlsafe_base64_encode or
force_text or make_token or notify_account_registration raises an
IntegrityError, the first will not catch it and the second will.

(Presumably, if form.save() finishes without an exception, then
subsequently form.is_valid() will be false, because now the user
exists.)

I don't like the fact that Django doesn't make it easy to catch
particular constraint violations.  I don't know of a good way to solve
that problem, but we have to deal with it.  This means we should both
double-check the inputs (as you're doing with form.full_clean() /
form.is_valid()), and also keep the 'try' body as small as possible.

**Comment by elfeto** [comment]
The following functions will not raise an `IntegrityError` because they don't touch the database.
 - force_bytes
 - urlsafe_base64_encode
 - force_text
 - make_token
 - notify_account_registration

Either way, I used your except/else method (I kinda like it)

**Comment by bemoody** [comment]
Thanks for your work on this and humoring my nitpicking!

**Pull request merged**
