### PR TITLE
Set shippable to debian buster

### PR DESCRIPTION
**Pull request by elfeto**
Please ignore this PR.

### CODE REVIEW

**Comment by tompollard** [comment]
Thanks! Is there a good reason to remove the following chunk?:

```
python:	
  - 3.7
```

Isn't it needed to match Python versions with our server?

**Comment by elfeto** [comment]
There is no reason to keep it since its in the "ci" configuration.

Either way, those lines are doing nothing with the image of Debian.

**Comment by tompollard** [comment]
Ah, I see, you've specified it in the CI section.

**Comment by elfeto** [comment]
This fixes #841

**Comment by elfeto** [comment]
Maybe an approach with a bit more finse could be added afterwards, but this works now :)

**Comment by bemoody** [comment]
Why did you change 'console/test_views.py' here?  Please do not make
irrelevant changes!!!

**Comment by elfeto** [comment]
That was removed to figure out what the problem is. Since the output is now dumped into a file, there is no need to silence that output.

I can do another commit/PR if you prefer that not being in this one.

**Comment by bemoody** [comment]
It's not your fault, but I am annoyed that @tompollard merged this
when you explicitly said "please ignore this".

**Comment by elfeto** [comment]
I apologize, I changed the title after it worked.

**Comment by tompollard** [comment]
Sorry @bemoody, just doing my best to be efficient! Shall we bring back the requirement for two people to approve a change before merging? I prefer this, and I think it's more feasible now.

**Comment by tompollard** [comment]
@bemoody Looking back at the changes, they seem pretty lightweight to me. I guess I didn't think there was much to worry about. I don't see the change to `console/test_views.py` that you mention above, so assume this refers to a change that was overwritten with a force push before we merged.

**Comment by bemoody** [comment]
Please pay attention to what you're merging, then. :/  If you look at
the log of what you merged, you can see it.  There are only two files
modified.

I mean, it's true that it's not a major change, but you really
shouldn't change the test code at the same time that you change the
test environment.

I'm glad it works!  But if someone creates an experimental branch and
opens a pull request that says "ignore this PR", it should be safe for
everyone to assume that it will *not*, in fact, be merged.  If the
author later decides that the changes are good ones and are ready to
be applied, then they can *close* the pull request and open a new one,
with a proper description for people to review.  We're not going to
run out of numbers.

**Comment by tompollard** [comment]
> Please pay attention to what you're merging, then. :/  If you look at
the log of what you merged, you can see it.  There are only two files
modified.

I reviewed the pull request before merging, as usual, and I was aware of the changes.  I'd misunderstood your comment above about `console/test_views.py`. I see your point about changing the test code and environment together, but as this relates to increased logging it seemed okay to me.

> Shall we bring back the requirement for two people to approve a change before merging? I prefer this, and I think it's more feasible now.

Any thoughts on this? I think it's a good idea, unless there are any strong objections.

**Pull request merged**
