### PR TITLE
Support new databases for WFDB

### PR DESCRIPTION
**Pull request by bemoody**
This allows access to new public databases via the traditional API, so that WFDB can be used to read them, e.g. via 'rdsamp -r mitdb/1.0.0/100' instead of 'rdsamp -r mitdb/100'.

In addition, consolidate the handling of Content-Security-Policy and make sure it applies to all static files.

nginx 'try_files' is always confusing, but I'm pretty sure this will work. :)

Given the files:

    /data/pn-static/published-projects/demobsn/1.0/scripts/lib.py
    /data/pn-static/published-projects/demobsn/1.0/foo.pdf
    /data/pn-static/physiobank/database/demobsn/udb/100s.hea
    /data/pn-static/physiobank/database/demobsn/foo.pdf

the following command:

    for path in \
      /physiobank/database/demobsn \
      /physiobank/database/demobsn/ \
      /physiobank/database/demobsn/foo.pdf \
      /physiobank/database/demobsn/udb \
      /physiobank/database/demobsn/udb/ \
      /physiobank/database/demobsn/udb/100s.hea \
      /physiobank/database/demobsn/1.0 \
      /physiobank/database/demobsn/1.0/ \
      /physiobank/database/demobsn/1.0/foo.pdf \
      /physiobank/database/demobsn/1.0/scripts \
      /physiobank/database/demobsn/1.0/scripts/ \
      /physiobank/database/demobsn/1.0/scripts/lib.py \
    ; do for url in http://localhost$path https://localhost$path; do
      echo $url;
      curl -s -I -k $url | tr -d \\r | \
          egrep -i '^HTTP|^Location:|^Content-Security-Policy:';
      echo; done; done

produces the output:
```
http://localhost/physiobank/database/demobsn
HTTP/1.1 301 Moved Permanently
Location: http://localhost/physiobank/database/demobsn/
Content-Security-Policy: sandbox; default-src 'self'

https://localhost/physiobank/database/demobsn
HTTP/2 301 
location: https://localhost/physiobank/database/demobsn/
content-security-policy: sandbox; default-src 'self'

http://localhost/physiobank/database/demobsn/
HTTP/1.1 301 Moved Permanently
Location: https://localhost/physiobank/database/demobsn/

https://localhost/physiobank/database/demobsn/
HTTP/2 302 
location: /content/demobsn/

http://localhost/physiobank/database/demobsn/foo.pdf
HTTP/1.1 200 OK

https://localhost/physiobank/database/demobsn/foo.pdf
HTTP/2 200 

http://localhost/physiobank/database/demobsn/udb
HTTP/1.1 301 Moved Permanently
Location: http://localhost/physiobank/database/demobsn/udb/
Content-Security-Policy: sandbox; default-src 'self'

https://localhost/physiobank/database/demobsn/udb
HTTP/2 301 
location: https://localhost/physiobank/database/demobsn/udb/
content-security-policy: sandbox; default-src 'self'

http://localhost/physiobank/database/demobsn/udb/
HTTP/1.1 200 OK
Content-Security-Policy: sandbox; default-src 'self'

https://localhost/physiobank/database/demobsn/udb/
HTTP/2 200 
content-security-policy: sandbox; default-src 'self'

http://localhost/physiobank/database/demobsn/udb/100s.hea
HTTP/1.1 200 OK
Content-Security-Policy: sandbox; default-src 'self'

https://localhost/physiobank/database/demobsn/udb/100s.hea
HTTP/2 200 
content-security-policy: sandbox; default-src 'self'

http://localhost/physiobank/database/demobsn/1.0
HTTP/1.1 301 Moved Permanently
Location: http://localhost/physiobank/database/demobsn/1.0/
Content-Security-Policy: sandbox; default-src 'self'

https://localhost/physiobank/database/demobsn/1.0
HTTP/2 301 
location: https://localhost/physiobank/database/demobsn/1.0/
content-security-policy: sandbox; default-src 'self'

http://localhost/physiobank/database/demobsn/1.0/
HTTP/1.1 200 OK
Content-Security-Policy: sandbox; default-src 'self'

https://localhost/physiobank/database/demobsn/1.0/
HTTP/2 200 
content-security-policy: sandbox; default-src 'self'

http://localhost/physiobank/database/demobsn/1.0/foo.pdf
HTTP/1.1 200 OK

https://localhost/physiobank/database/demobsn/1.0/foo.pdf
HTTP/2 200 

http://localhost/physiobank/database/demobsn/1.0/scripts
HTTP/1.1 301 Moved Permanently
Location: http://localhost/physiobank/database/demobsn/1.0/scripts/
Content-Security-Policy: sandbox; default-src 'self'

https://localhost/physiobank/database/demobsn/1.0/scripts
HTTP/2 301 
location: https://localhost/physiobank/database/demobsn/1.0/scripts/
content-security-policy: sandbox; default-src 'self'

http://localhost/physiobank/database/demobsn/1.0/scripts/
HTTP/1.1 200 OK
Content-Security-Policy: sandbox; default-src 'self'

https://localhost/physiobank/database/demobsn/1.0/scripts/
HTTP/2 200 
content-security-policy: sandbox; default-src 'self'

http://localhost/physiobank/database/demobsn/1.0/scripts/lib.py
HTTP/1.1 200 OK
Content-Security-Policy: sandbox; default-src 'self'

https://localhost/physiobank/database/demobsn/1.0/scripts/lib.py
HTTP/2 200 
content-security-policy: sandbox; default-src 'self'

```

### CODE REVIEW

**Comment by Lucas-Mc** [comment]
This sounds exciting! It also looks like good news for all the other implementations of WFDB (matlab, python) too! I'll have to take a look! (:

**Comment by bemoody** [comment]
Thanks... I saw that you've been trying to work around this in the
matlab toolbox by trying to cache everything locally, which may work
but is a bit awkward.

I have mixed feelings about supporting HTTP versus HTTPS, and about
maintaining old APIs/URLs versus promoting the newer and clearer ones,
but I still think keeping old software working is a worthy goal. :)

**Comment by Lucas-Mc** [comment]
Haha, I agree! You're not the only one who thought that caching
everything felt a bit awkward! 😂 Keeping the old software working is
always good for the community and for us since it makes our lives easier!

Just looking through this now and understand your initial comment
regarding its functionality and will start looking at the changed files next

**Comment by Lucas-Mc** [comment]
Just reading this; it's a shame about the PDFs! A lot of browsers seems to have issues with PDFs in general: my Safari just shows a blank page, my Chrome says an "extension" is blocking it even when extensions are disabled, my Firefox... works! Anyway, I'll keep looking but your fix seems good for now!

**Comment by Lucas-Mc** [comment]
This looks great! I was almost confused with the `/physiobank/database` location block since new content is at `/files` but then I looked at your `try_files` and it all makes sense! I like how you first check the non-legacy projects to get updated content if available. Excited to see the results! 👍

**Comment by tompollard** [comment]
Ah, this is the change that has started to block CITI certificates from appearing in my browser! They open in Firefox, but I get an error when trying to open them in Chrome.

**Comment by bemoody** [comment]
This particular change isn't deployed yet and shouldn't affect media
files in any way.  The problems with PDF files have been around for a
long time.  :/

**Comment by tompollard** [comment]
> This particular change isn't deployed yet and shouldn't affect media files in any way.  The problems with PDF files have been around for a long time.

It's possible that something has changed on my side (e.g. I did update my OS today), but I have definitely gone from being able to view PDFs to not being able to view PDFs. Not a big issue though...easy enough to download instead or to use a different browser.

Are we sure this isn't deployed? It is merged and pushed to the server.

**Comment by bemoody** [comment]
I mentioned this in passing in issue #1024.  There are a few possible
approaches we could take:

- If the report is a valid PDF training report from CITI, we could link
  directly to the PDF on citiprogram.org instead of the copy on
  physionet.org.

- We could change the link to download the file instead of viewing it
  inline (a nuisance if you want to quickly review it.)

- We could arrange to serve untrusted PDF files from a separate
  domain (e.g. *.mit.edu) to avoid the security issues.

- We could attempt to sanitize the PDF, or convert it to HTML.

**Comment by bemoody** [comment]
> Are we sure this isn't deployed? It is merged and pushed to the
> server.

System configuration files aren't installed automatically.  I've just
installed this along with Felipe's recent changes for weekly database
transfers, so it should be working *now*, but it wasn't a few minutes
ago. :)

**Comment by tompollard** [comment]
Thanks, increased security is good and not displaying (potentially unsafe) PDFs in the browser is a minor inconvenience. The direct links to citiprogram.org are better in many ways (not just security wise, but trust wise too). One small tweak that I have been meaning to make is to display the citiprogram.org links in the application profile during review (not yet done).

**Pull request merged**
