### PR TITLE
Adds another sorting for credential application #955

### PR DESCRIPTION
**Pull request by Lucas-Mc**
This slightly modifies the current sorting of credential applications from references being contacted or not to (1) reference is known but not contacted (2) reference is not known and not contacted (3) reference is known and contacted. This separates each category by changing the font color of the application username in the application list to Black for (1), Red for (2), and Green for (3).

### CODE REVIEW

**Comment by elfeto** [comment]
I added some DUMMY data to the fixture to to check this and future checks.
This includes:
  - 72 new applications.
  - 200 users (same password)
  - 24 applications with lceli@yahoo.com as the reference email (same as rgmark)
  - 37 applications have the reference contacted.
  - 35 applications with no reference

**Comment by elfeto** [comment]
Just as an FYI for the future... the code I used to generate the dummy data is:
```
from user.models import User, CredentialApplication
from django.db.utils import IntegrityError
import names
from random import randrange
import barnum
from django.utils.crypto import get_random_string

for a in range(200):
    first = names.get_first_name()
    last = names.get_last_name()
    try:
        user = User.objects.create_user(first_names=first, last_name=last, email="{0}_{1}@fake_gmail.com".format(first, last), password="Tester11!", username=first+last, is_active=True)
    except IntegrityError:
        user = None
    if a % 3 == 0 and user:
        category = randrange(3, 7)
        ref = randrange(4)
        if category in [0, 1]:
            ref = 0
        inst = barnum.create_company_name()
        title = barnum.create_job_title()
        city_state = barnum.create_city_state_zip()
        h = CredentialApplication.objects.create(
            user=user, first_names=user.profile.first_names, last_name=user.profile.last_name,
            researcher_category=category, organization_name=inst,
            job_title=title, city=city_state[1], state_province=city_state[2],
            country="US", zip_code=city_state[0], training_completion_date=barnum.gen_data.datetime.date(2020, randrange(1, 13), randrange(1, 29)),
            training_course_name="CITI Course", reference_category=ref,
            reference_name=names.get_full_name(), reference_email=barnum.create_email(),
            reference_title=barnum.create_job_title(), research_summary=barnum.create_paragraphs(),
            slug=get_random_string(20))
    if (a % 3 != 0) and (a % 4 == 0) and user:
        category = randrange(7)
        ref = randrange(4)
        if category in [0, 1]:
            ref = 0
        inst = barnum.create_company_name()
        title = barnum.create_job_title()
        city_state = barnum.create_city_state_zip()
        h = CredentialApplication.objects.create(
            user=user, first_names=user.profile.first_names, last_name=user.profile.last_name,
            researcher_category=category, organization_name=inst,
            job_title=title, city=city_state[1], state_province=city_state[2],
            country="US", zip_code=city_state[0], training_completion_date=barnum.gen_data.datetime.date(2020, randrange(1, 13), randrange(1, 29)),
            training_course_name="CITI Course", research_summary=barnum.create_paragraphs(),
            slug=get_random_string(20))
    if a % 6 == 0 and user:
        app = CredentialApplication.objects.last()
        app.reference_contact_datetime = app.training_completion_date
        app.save()
    if a % 9 == 0 and user:
        app = CredentialApplication.objects.last()
        app.reference_email = 'lceli@yahoo.com'
        app.save()
```

Then I changed some dates to have different application/ref_contact dates

**Comment by bemoody** [comment]
I have no substantive comments on this, but let's take a moment to
appreciate the quality of these fake applications:

> {
>   "model": "user.credentialapplication",
>   "pk": 2,
>   "fields": {
>     "slug": "5rDeC8Om9dBJTeJN91y2",
>     "application_datetime": "2020-03-29T21:51:08.356Z",
>     "user": 5,
>     "first_names": "James",
>     "last_name": "Lawson",
>     "researcher_category": 5,
>     "organization_name": "Alpha Technology Adventure",
>     "job_title": "Corporate Attorney",
>     "city": "O Brien",
>     "state_province": "TX",
>     "country": "US",
>     "webpage": "",
>     "zip_code": "79539",
>     "suffix": "",
>     "training_course_name": "CITI Course",
>     "training_completion_date": "2020-06-25",
>     "training_completion_report": "",
>     "course_category": null,
>     "course_info": "",
>     "reference_category": 3,
>     "reference_name": "Margaret Ramos",
>     "reference_email": "lceli@yahoo.com",
>     "reference_title": "Manager Bowling Alley",
>     "status": 0,
>     "reference_contact_datetime": "2020-06-25T04:00:00Z",
>     "reference_response_datetime": null,
>     "reference_response": 0,
>     "reference_response_text": "",
>     "research_summary": "Augue feugait dolore iustoodio hendrerit dolor nostrud ipsum nulla tincidunt qui. Dignissim ut commodo enim consectetuer elitsed in vel delenitaugue etaccumsan. Esse tation eum etaccumsan volutpat te. Wisi et vulputate sit qui eufeugiat te veniam nulla aliquip luptatumzzril in. \n\n",
>     "project_of_interest": null,
>     "decision_datetime": null,
>     "responder": null,
>     "responder_comments": ""
>   }
> },

:)

**Comment by tompollard** [comment]
Thanks Barnum (https://pypi.org/project/barnum/).

**Comment by tompollard** [comment]
Felipe says that this is working, so it sounds like we should be good to merge! Please could you check for PEP8 before we do?

**Comment by Lucas-Mc** [comment]
> Felipe says that this is working, so it sounds like we should be good to merge! Please could you check for PEP8 before we do?

Added PEP8 fixes for the changed code!

**Pull request merged**
