### PR TITLE
Revert Bump cryptography from 36.0.1 to 39.0.1 #1859

### PR DESCRIPTION
**Pull request by tompollard**
There is an issue with #1859, which bumped the cryptography package. It looks like the problem relates to openssl. The change is raising an upgrade error when pushing to the server:

```
remote: * Installing new requirements...
remote: Traceback (most recent call last):
remote:   File "/physionet/python-env/physionet/bin/pip3", line 5, in <module>
remote:     from pip._internal.cli.main import main
remote:   File "/physionet/python-env/physionet/lib/python3.9/site-packages/pip/_internal/cli/main.py", line 10, in <module>
remote:     from pip._internal.cli.autocompletion import autocomplete
remote:   File "/physionet/python-env/physionet/lib/python3.9/site-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
remote:     from pip._internal.cli.main_parser import create_main_parser
remote:   File "/physionet/python-env/physionet/lib/python3.9/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
remote:     from pip._internal.cli import cmdoptions
remote:   File "/physionet/python-env/physionet/lib/python3.9/site-packages/pip/_internal/cli/cmdoptions.py", line 23, in <module>
remote:     from pip._vendor.packaging.utils import canonicalize_name
remote:   File "/physionet/python-env/physionet/lib/python3.9/site-packages/pip/_vendor/__init__.py", line 94, in <module>
remote:     vendored("requests.packages.urllib3.contrib.pyopenssl")
remote:   File "/physionet/python-env/physionet/lib/python3.9/site-packages/pip/_vendor/__init__.py", line 36, in vendored
remote:     __import__(modulename, globals(), locals(), level=0)
remote:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
remote:   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
remote:   File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
remote:   File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
remote:   File "<frozen zipimport>", line 259, in load_module
remote:   File "/usr/share/python-wheels/urllib3-1.26.5-py2.py3-none-any.whl/urllib3/contrib/pyopenssl.py", line 50, in <module>
remote:   File "/physionet/python-env/physionet/lib/python3.9/site-packages/OpenSSL/__init__.py", line 8, in <module>
remote:     from OpenSSL import crypto, SSL
remote:   File "/physionet/python-env/physionet/lib/python3.9/site-packages/OpenSSL/crypto.py", line 1517, in <module>
remote:     class X509StoreFlags(object):
remote:   File "/physionet/python-env/physionet/lib/python3.9/site-packages/OpenSSL/crypto.py", line 1537, in X509StoreFlags
remote:     CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
remote: AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
remote: error: hook declined to update refs/heads/staging
```

This pull request reverts the previous change until we work out a fix.

### CODE REVIEW

**Comment by tompollard** [comment]
Hmm, need to look into this a little more. Going to close the PR for now.

**Comment by bemoody** [comment]
I'm a little confused because this doesn't revert *all* the changes in poetry.lock
```
$ git diff 2a8634f:./poetry.lock dbcbc12:./poetry.lock
diff --git a/poetry.lock b/poetry.lock
index e3b603de..023f0341 100644
--- a/poetry.lock
+++ b/poetry.lock
@@ -265,12 +265,14 @@ files = [
 cffi = ">=1.12"
 
 [package.extras]
-docs = ["sphinx (>=1.6.5,!=1.8.0,!=3.1.0,!=3.1.1)", "sphinx-rtd-theme"]
+docs = ["sphinx (>=5.3.0)", "sphinx-rtd-theme (>=1.1.1)"]
 docstest = ["pyenchant (>=1.6.11)", "sphinxcontrib-spelling (>=4.0.1)", "twine (>=1.12.0)"]
-pep8test = ["black", "flake8", "flake8-import-order", "pep8-naming"]
+pep8test = ["black", "check-manifest", "mypy", "ruff", "types-pytz", "types-requests"]
 sdist = ["setuptools-rust (>=0.11.4)"]
 ssh = ["bcrypt (>=3.1.5)"]
-test = ["hypothesis (>=1.11.4,!=3.79.2)", "iso8601", "pretend", "pytest (>=6.2.0)", "pytest-cov", "pytest-subtests", "pytest-xdist", "pytz"]
+test = ["hypothesis (>=1.11.4,!=3.79.2)", "iso8601", "pretend", "pytest (>=6.2.0)", "pytest-benchmark", "pytest-cov", "pytest-shard (>=0.1.2)", "pytest-subtests", "pytest-xdist", "pytz"]
+test-randomorder = ["pytest-randomly"]
+tox = ["tox"]
 
 [[package]]
 name = "django"
```

**Comment by tompollard** [comment]
Odd, good catch. Let me take another look at this.

**Comment by tompollard** [comment]
I'd reverted https://github.com/MIT-LCP/physionet-build/pull/1859/commits/0e112488e3b1f5cc66310e0ad2715480d5039fd5 which I think was responsible for your comment above. This set of changes should now take us back to the state of packages prior to bumping cryptography.

**Comment by bemoody** [comment]
Thanks.  The plan in short is that (since this package seems to have broken pip in some strange way) we'll revert to the previous set of requirements, by manually re-creating the virtualenv prefix on the staging and live servers.

**Pull request merged**
