### PR TITLE
Platform Training and Quiz 1

### PR DESCRIPTION
**Pull request by harryface**
This is for the on platform training.

It was a vey big PR and creating this as a way to break it into bits.

This Part 1:
- Created a new training app, with its model, admin, fixtures etc

The [Part 2](https://github.com/MIT-LCP/physionet-build/pull/1889) will be having this as a Parent and will contain the logic:
- Population of Training, its quiz and content body via JSON.
- On major version change, sets all older version training to 30 days expiry, and sends a mail to users.
- The views logic for displaying and undergoing the training.

To take OP Trainings
Screenshot 2023-02-07 at 08 41 46

To create OP Trainings
Screenshot 2023-02-28 at 07 43 03

### CODE REVIEW

**Comment by bemoody** [comment]
This pull request needs a bit more explanation of what you're doing and why.

Uploading images is a complicated subject, and the way you're trying to implement it here is *not going to work* for a lot of reasons.

Uploading images seems like quite a separate issue from everything else you're trying to do here.  Please try to first get the on-platform training feature working by itself, without any special support for images.  After that feature is implemented, then we can think about ways to (make it easier to) embed images in the training content.

**Comment by superryeti** [comment]
## **Workflow**

Here is the workflow of how to use the feature

### **Users**
1. Training Admin 
    Training Admin(someone with change training access and access to admin console) 
    Admin can login to website and visit the Admin console > Training > OP Training.
    
    Here they can see existing on platform training and create or update an existing training.

    1.1 Creating a new Training
        To Create a new Training, admin will click on the `Create/Update Training` button, and select `Create New Training` from dropdown, and upload the training data in .json format.

     [create json example](https://github.com/MIT-LCP/physionet-build/pull/1887/files#diff-d2cf18e84ea2d305d3e81a8fee2e0bd5606f36ae458cb38fd9c7563fbbd7c447R1-R40)
        
    1.2 Updating an existing Training
        For update process is same, the admin will select the training they want to update in the dropdown and upload the json that contains updated training data

      [upload json example]( https://github.com/MIT-LCP/physionet-build/pull/1887/files#diff-badadda4bc7a80e0a98b9277e029dd11b6d950bbb5723713caecb31701339286R1-R40)
    
    Quick notes:
        a. For updates please use semantic versioning, if there is a small change, then please increase the version with a patch like 1.0 to 1.1. But if you have made a major change in training please update the main version number like 1.5 > 2.0. When you do a major update, all existing training certificate of users for the updated training will expire after 30 days. users are sent email requesting them to take the training again.
        b. Order works in a very simple way, content and quiz load according to order(for example if a quiz had an order 0, and the content has order 1, the quiz will appear before the order)
        c. Admin can add as many content and quizes as they want.
        d. For every update, admin will need to include all the content,quiz(i.e the implementation will not fetch content or quiz from previous version)
        
2. User
   User is anyone who is logged in

   User can login and go to their account settings > Training and select an on platform training and click start to begin training
   Based on the training, users will see a series of content, quizzes and will have an option to submit the training and the end.
   Users can read the content and navigate the training by clicking Next, Back button.
   If a user comes across a quiz, then they will not be able to navigate forward unless they answer the quiz correctly.

   Quick notes
   a. There is no resume feature(which means if the user refreshes the tab, they will lose progress.)



## **Models**

The idea here is that we will use existing `user.TrainingType` to create a new on platform Training, this lets us add the onplatform training feature without making any changes to existing codebase. 

To track the content, quiz for a Training, we have model `training.OnPlatformTraining` which uses a field `version`  and `training_type`(foreign key to `user.TrainingType`)

For example,
Suppose we want to create a onplatform training called `PhysioNet CyberSecurity 101`, then we will create a new `user.TrainingType` with name `PhysioNet CyberSecurity 101` and then we will create a new `training.OnPlatformTraining` with `version` 1.0 and `training_type` as the newly created `user.TrainingType`. For content and quiz we will create a new model `training.ContentBlock`, `training.Quiz` and `training.QuizChoice` respectively.

If there is an update to the training `PhysioNet CyberSecurity 101`, then we will create a new `training.OnPlatformTraining` with `version` 2.0 and `training_type` as the newly created `user.TrainingType`. For content and quiz we will create a new model `training.ContentBlock`, `training.Quiz` and `training.QuizChoice` respectively.

on the frontend, we will use the `user.TrainingType` to fetch the latest `training.OnPlatformTraining` and then use the `training.OnPlatformTraining` to fetch the related content and quiz.


## How is the take training implemented?

For training, when a user loads the training page, we will load  all the content, quiz and sort them serially. We will then show the first content or quiz to the user. When the user clicks next, we will show the next content or quiz. If the user clicks back, we will show the previous content or quiz. If the user clicks submit, we will check if the user has completed all the content and quiz, if yes, then we will mark the training as completed and send an email to the user.

**Questions**
1. For the resume training feature, do we want to store the user's progress locally or in database?(my guess is Database as it would provide better user experience). if we want to store the progress in database, i think we could have a mode like 

```

class OnPlatformTrainingProgress(models.Model):
    user = models.ForeignKey('user.User',
                             on_delete=models.CASCADE, related_name='op_training_progresses')
    training = models.ForeignKey('training.OnPlatformTraining',
                                 on_delete=models.CASCADE, related_name='progresses')
    completed = models.BooleanField(default=False)

    content_blocks = models.ManyToManyField('training.ContentBlock', related_name='progresses')
    quizzes = models.ManyToManyField('training.Quiz', related_name='progresses')

    class Meta:
        unique_together = ('user', 'training')
```

and track the question and section the user has completed here. We can use this to show the progress to the user as well(like 10% course completed or 3/10 modules , 2/5 quiz completed completed)

2. Display the Training content summary on the Training detail page?(example below from tpcs2core)

image

3. Do we want to grade users with score like 90% or something? and require them to have a minimum passing percentage(Currently, we require them to have 100% scores). Maybe this is something desirable after the first PR. 

4. I remember there was discussion about moving the On platform training outside of settings, What if add a `On Platform Training ` on the Nav bar and have a dedicated page for Training?(i can make a mockup image of somekind)

   4.1 We could show a list of Training Available to user, list their certificates and completion date, expiry date.
   4.2 Users can then take a training from the list
   
   Maybe something like the Physionet Search page https://physionet.org/content/


**TODOS**
1. Resume feature/Track Training progress for a user
2. Prevent user from taking the test twice(in case they have completed it before) or atleast remind them that they already took the test successfully

**Notes from Harry**

- Add a create training type button *
- View all Training with button beside asking to make it OP *
- Modify the settings training page to display the latest versions

**Comment by superryeti** [comment]
@alistairewj @bemoody @tompollard   Ready for feedback/suggestions. Please check the note above

**Comment by superryeti** [comment]
Quick note on what i am working on currently

1. Add modules before content, quizzes(so OnPlatformTraining --> Modules --> Content, Quizzes)
  and update the code to use modules and have a Training detail page that shows the details about training, modules, no of content, quizzes under the modules.
2. Saving Users Progress and letting them resume training later.

**Comment by superryeti** [comment]
Closing this because we decided to open two new PRs with simplified and squashed commits 



PR 1: Add create training from admin console by uploading json 
https://github.com/MIT-LCP/physionet-build/pull/1950

PR 2: implement take training feature and resume training feature for user 
https://github.com/MIT-LCP/physionet-build/pull/1951

**Pull request closed without merging**
