### PR TITLE
Rearranged the training frontend into certification & training

### PR DESCRIPTION
**Pull request by Rutvikrj26**
Changes: The Pull Request rearranges the frontend for the user's settings page. Initially, all the information related to training was provided in the training tab. I've refactored it into two parts : Trainings & Courses. The training tab now only gives the information on the status of the trainings that the user has. Submitting a training is now shifted to the course tab. 

Reason: As we add the option to take course to the platform, the training page becomes very cluttered and hard to navigate. In order to improve the user workflow and experience, @tompollard suggested that we break the training page into two - one that shows status of the trainings, and another that let's user add training or take courses.

### CODE REVIEW

**Comment by tompollard** [comment]
This is how the pages look after this change:

### Courses

Screenshot 2023-09-05 at 5 25 52 PM

### Training

Screenshot 2023-09-05 at 5 25 43 PM

**Comment by tompollard** [comment]
@Rutvikrj26 Just adding a quick thought in advance of our chat in 10min.

On the Training page, instead of the yellow box saying "The following training is under review...", how about using the same formatting as the "Active, Expired, Reject" subheaders? 

e.g. something like this, though perhaps "Under review" would be better at start of list?

Screenshot 2023-09-11 at 11 48 50 AM

**Comment by tompollard** [comment]
Just to keep everyone updated, our plan is to split training into two tabs in the menu: "Training" and "Certification". 

- The Training tab provides options for completing training (both guidance for CITI training and in future options for on-board training). 
- The Certification tab provides a list of active, expired, etc certification. 

Please shout if you dislike this approach or if you have a better suggestion.

@bemoody @briangow @alistairewj

**Comment by Rutvikrj26** [comment]
The trainings are now logically broken down into two part :
1. Certifications : The page that lets the viewer see each certification he has, their status and further details
image

2. Training : The page that lets user submit trainings (and take courses in the subsequent PR).
image

**Comment by tompollard** [comment]
Looks good, thanks! It looks like you have completely restyled physionet-django/user/templatetags/user_templatetags.py, physionet-django/user/urls.py, physionet-django/user/views.py. 

Although I'm tempted to merge anyway, I probably shouldn't do because it's going to cause some horrible conflicts for anyone working on these files. Please could you update the PR to only apply formatting changes to lines that you've touched?

**Comment by Rutvikrj26** [comment]
Thanks for bringing this to my notice!
Black had automatically changed the code for the entire file on save, and I missed that.
Fixed it.

**Comment by tompollard** [comment]
@Rutvikrj26 looks like some of the style checks are failing. When you have fixed the changes, please could you squash the commits?

**Comment by tompollard** [comment]
@Rutvikrj26 Not sure what happened in the updates, but I don't see the "Certification" tab at: http://localhost:8000/settings/

**Comment by Rutvikrj26** [comment]
@tompollard, it still shows me in my development environment. 
I'll try setting the repo up from scratch to see what the issue might be.

**Comment by tompollard** [comment]
I'm sorry @Rutvikrj26, I tried again and it now seems to be working as expected. Feel like I'm going mad, because it definitely wasn't 10min ago! Seems like the issue was on my side...

**Comment by tompollard** [comment]
(i think probably a caching issue, sorry)

**Pull request merged**
