### PR TITLE
Set ActiveProject publish as atomic

### PR DESCRIPTION
**Pull request by elfeto**
Convert the ActiveProject publish function as atomic, either all passes, or all fails.

### CODE REVIEW

**Comment by elfeto** [comment]
After the phone conversation, I moved all NON database related actions (file related) outside the atomic transaction.

**Comment by bemoody** [comment]
On 2/18/20, Felipe Torres <notifications@github.com> wrote:
> After the phone conversation, I moved all NON database related actions (file
> related) outside the atomic transaction.

Why?  That doesn't sound like an improvement. :(

**Comment by elfeto** [comment]
Up to my understanding of Django's atomic transaction, will only handle database transactions, and not files. Since most of the publish is DB related, but the end in which the files are managed, then I just added transaction atomic to all the DB related, and just bumped down to a if statement the files. 

That was the closest thing that I can think of to make publish an atomic transaction.

I'm open to ideas.

**Comment by bemoody** [comment]
Well, it's true that the atomic transaction won't roll back changes to
the filesystem.

But, if the FS operations fail then we want publication to fail (no
changes made to the DB).  And if the DB operations fail then we want
the files to remain where they are.

So what are the possible failure modes here?

Maybe to be extra paranoid, it should be

   rename directory
   try
      with atomic transaction
         do stuff
   except
      rename directory back where it was

?

**Comment by elfeto** [comment]
I just did the try except with the rename in the beginning.

**Comment by bemoody** [comment]
(Looks like my reply was dropped somewhere?  Sorry if this message gets duplicated.)

Thanks!

The rmdir is probably unnecessary (and the isdir is definitely
unnecessary) but if you do want to do the rmdir then please update the
comment accordingly.

(Bear in mind that the rmdir will fail with ENOTEMPTY if the directory
isn't empty - i.e., there is already another published version.)

I would advise you to write:

    except:
        ...
        raise

rather than:

    except Exception as exception:
        ...
        raise exception

For a few reasons: (1) in cases like this, we want to catch all
exceptions (BaseException, not Exception); (2) "raise exception" adds
clutter to the stack trace whereas "raise" doesn't; (3) keep it short
and sweet.


It's probably not useful here, but I just learned about a Django
feature that may be useful in some cases:
'django.db.transaction.on_commit' to do something only after preceding
changes are successfully committed to the database.

**Comment by elfeto** [comment]
> 'django.db.transaction.on_commit' to do something only after preceding

Interesting

**Comment by bemoody** [comment]
Looks great - thanks!

**Pull request merged**
