### PR TITLE
Search button

### PR DESCRIPTION
**Pull request by bemoody**
Felipe, in commit aaa3fb7174a14aeeb5177dad6e926373cb64ebc0 you undid my changes, without giving any explanation or making a pull request.  Please don't do that.

### CODE REVIEW

**Comment by elfeto** [comment]
Sorry for that, but the search bar looked like this. Thought it was a simple fix, but apparently I got the icon too close to the search bar. 
Screen Shot 2019-05-20 at 6 42 12 PM

**Comment by bemoody** [comment]
What browser?  Did you clear cache?

**Comment by elfeto** [comment]
So it seemed fine when i tried it in my local pc, and it looks fine now again. 
Before it was in chrome, and I believe I did, but might have done something wrong.

Lets try again :D and see if its all in my machine

**Comment by elfeto** [comment]
Seems fine, sorry about that.... might not have cleared the cache apparently :(

**Pull request merged**
