### PR TITLE
MK2: Switch Shippable to run tests on Postgres (ref #677) #680

### PR DESCRIPTION
**Pull request by tompollard**
This is a first attempt at switching Shippable to run tests on Postgres instead of SQLite (ref #677). I'm expecting this to fail on first attempt, but having the pull request open will help me to troubleshoot. Please don't merge for now!

### CODE REVIEW

**Comment by tompollard** [comment]
The tests are now running on Postgres. They are failing with what looks like an error on the dev branch: 

```
  Applying project.0030_auto_20190807_1220...Traceback (most recent call last):
  File "/root/venv/3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedFunction: operator does not exist: boolean = integer
LINE 1: ...shedproject" WHERE "project_publishedproject"."featured" = 1
                                                                    ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/root/venv/3.7/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/root/venv/3.7/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/venv/3.7/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/venv/3.7/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/root/src/github.com/MIT-LCP/physionet-build/physionet-django/user/management/commands/resetdb.py", line 64, in handle
    call_command('migrate')
  File "/root/venv/3.7/lib/python3.7/site-packages/django/core/management/__init__.py", line 148, in call_command
    return command.execute(*args, **defaults)
  File "/root/venv/3.7/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/root/venv/3.7/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/root/venv/3.7/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 234, in handle
    fake_initial=fake_initial,
  File "/root/venv/3.7/lib/python3.7/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/root/venv/3.7/lib/python3.7/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/root/venv/3.7/lib/python3.7/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/root/venv/3.7/lib/python3.7/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/root/venv/3.7/lib/python3.7/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/root/src/github.com/MIT-LCP/physionet-build/physionet-django/project/migrations/0030_auto_20190807_1220.py", line 12, in save_featured
    for p in projects:
  File "/root/venv/3.7/lib/python3.7/site-packages/django/db/models/query.py", line 274, in __iter__
    self._fetch_all()
  File "/root/venv/3.7/lib/python3.7/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/root/venv/3.7/lib/python3.7/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/root/venv/3.7/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1100, in execute_sql
    cursor.execute(sql, params)
  File "/root/venv/3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/root/venv/3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/root/venv/3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/root/venv/3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/venv/3.7/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/venv/3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: operator does not exist: boolean = integer
LINE 1: ...shedproject" WHERE "project_publishedproject"."featured" = 1
                                                                    ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
```

**Comment by elfeto** [comment]
I fixed that with the latest merge, but its still broken for another reason....

ALSO... why did you added so many --hash=sha25 ??

**Comment by tompollard** [comment]
> ALSO... why did you added so many --hash=sha25 ??

The hashes are for different architectures (https://pypi.org/pypi/psycopg2/json), generated with hashin (https://pypi.org/project/hashin/). Verbose output from hashin below:

```
* Found hash for https://files.pythonhosted.org/packages/2b/c7/8875bbe479ddd6f55764ba243abc4c348ee0924a90a48a6abe7620b2cb61/psycopg2-2.8.3-cp27-cp27m-win32.whl
*   Hash 2315e7f104681d498ccf6fd70b0dba5bce65d60ac92171492bfe228e21dcc242
* Found hash for https://files.pythonhosted.org/packages/c7/67/6e6cc1ff49dc4a782b816f9f28904939dec5c97a4691d2b664d469c6772c/psycopg2-2.8.3-cp27-cp27m-win_amd64.whl
*   Hash 4b5417dcd2999db0f5a891d54717cfaee33acc64f4772c4bc574d4ff95ed9d80
* Found hash for https://files.pythonhosted.org/packages/05/e9/1ca624f39b7264886c448651747671606c3331aee1d0185bd5452126c617/psycopg2-2.8.3-cp34-cp34m-win32.whl
*   Hash b1b8e41da09a0c3ef0b3d4bb72da0dde2abebe583c1e8462973233fd5ad0235f
* Found hash for https://files.pythonhosted.org/packages/61/4e/9fe96e616730954dfc87d8d1f52cbe3e458484cbe7ac34f52cfec9da7c1c/psycopg2-2.8.3-cp34-cp34m-win_amd64.whl
*   Hash 640113ddc943522aaf71294e3f2d24013b0edd659b7820621492c9ebd3a2fb0b
* Found hash for https://files.pythonhosted.org/packages/fe/06/cbc1c1cf8704bdd1cf9e338c5740f58918992d89b42ad832feb5197666fd/psycopg2-2.8.3-cp35-cp35m-win32.whl
*   Hash 128d0fa910ada0157bba1cb74a9c5f92bb8a1dca77cf91a31eb274d1f889e001
* Found hash for https://files.pythonhosted.org/packages/1f/ee/5728d5bb8bf85e3c5f1dfacb8ebdd98119f8c0c61a4c4d4ed88cd7bd5210/psycopg2-2.8.3-cp35-cp35m-win_amd64.whl
*   Hash f0e6b697a975d9d3ccd04135316c947dd82d841067c7800ccf622a8717e98df1
* Found hash for https://files.pythonhosted.org/packages/68/f8/e11270d59030163fb849b0de8ead6d2ba380990491e77998dfd3d69663e0/psycopg2-2.8.3-cp36-cp36m-win32.whl
*   Hash 8dceca81409898c870e011c71179454962dec152a1a6b86a347f4be74b16d864
* Found hash for https://files.pythonhosted.org/packages/b2/85/a8ea3d7d7d3ee07aa30c5d8d098022ed17fdba8d360c42d46069d72c9500/psycopg2-2.8.3-cp36-cp36m-win_amd64.whl
*   Hash d3a27550a8185e53b244ad7e79e307594b92fede8617d80200a8cce1fba2c60f
* Found hash for https://files.pythonhosted.org/packages/69/21/57e12f1c47d8a540e502f098f5ab5d54db099c95fbaa5791239ac4e8a86f/psycopg2-2.8.3-cp37-cp37m-win32.whl
*   Hash 227fd46cf9b7255f07687e5bde454d7d67ae39ca77e170097cdef8ebfc30c323
* Found hash for https://files.pythonhosted.org/packages/3b/b4/b6db75663e1c73bb6190cbcbb02f94a36c574b813a353446087cbdf43712/psycopg2-2.8.3-cp37-cp37m-win_amd64.whl
*   Hash cb407fccc12fc29dc331f2b934913405fa49b9b75af4f3a72d0f50f57ad2ca23
* Found hash for https://files.pythonhosted.org/packages/5c/1c/6997288da181277a0c29bc39a5f9143ff20b8c99f2a7d059cfb55163e165/psycopg2-2.8.3.tar.gz
*   Hash 897a6e838319b4bf648a574afb6cabcb17d0488f8c7195100d48d872419f4457
```

I can remove some if you like, though doesn't it make sense to list the whole lot to make it easy for people to build on their own systems?

**Comment by elfeto** [comment]
I don't believe so. I understand your desire to make this easy to build in other people systems but we are only adding the necessary things, those additional "sha" would be un-needed. Also it would be ideal to know which package we are using. 

BTW, all of the other modules have a single or up to three different "sha", not the 10 or more than exists for each package. 

If reloading the fixtures is not necessary, then why would you comment it out instead of removing them?

**Comment by lbulgarelli** [comment]
Working now :)

**Comment by elfeto** [comment]
This breaks the regular tests, or at least for me.
the output of: "./manage.py test -v3" 
will end up in this: "FAILED (failures=6, errors=29, skipped=2)"

I haven't looked into the code nor anything.

**Comment by lbulgarelli** [comment]
> This breaks the regular tests, or at least for me.
> the output of: "./manage.py test -v3"
> will end up in this: "FAILED (failures=6, errors=29, skipped=2)"
> 
> I haven't looked into the code nor anything.

The latest commit should solve that.

One thing to keep in mind is that now the changes you make changes to the database when developing you might end up have the tests failing, as the test database is mirroring it.

Previously that did not happen because the fixtures were reloaded for each test, and that is apparently broken when using postgres.

**Pull request merged**
