### PR TITLE
Add citation details to "project published" notification email

### PR DESCRIPTION
**Pull request by tompollard**
Minor change in response to #1068 to add citation details to the email that is sent to authors upon publication. The email now reads:

```
We are delighted to inform you that your project entitled "Test
database" (version 1.0) has been published on PhysioNet. The project
is available at: https://doi.org/10.7966/ymcx-6e03

The formal citation is:
Bot A. Test database (version 1.0). PhysioNet. 2020. Available from:
https://doi.org/10.7966/ymcx-6e03.

We encourage you to share these details to increase your work's
visibility in the research community. Thanks for choosing to
publish with PhysioNet.
```

### CODE REVIEW

**Comment by tompollard** [comment]
Minor change after re-reading the email (final sentence has been removed). It now says:

```
We are delighted to inform you that your project entitled "Test
database" (version 1.0) has been published on PhysioNet. The project
is available at: https://doi.org/10.7966/ymcx-6e03

The formal citation is:
Bot A. Test database (version 1.0). PhysioNet. 2020. Available from:
https://doi.org/10.7966/ymcx-6e03.

We encourage you to share these details to increase your work's
visibility in the research community.
```

**Comment by bemoody** [comment]
Do you have a particular reason for using the Vancouver style?  It
seems odd to use something different here from what is shown on the
site itself.

It's also awkward that you're changing the Python API here in order to
change the result at the template level.  I think you could write
instead {{project.citation_text_all.Vancouver}} if that's what you
want.

Simply using striptags will break apostrophes (as well as & " < > if
those were allowed.)  What we want is to also pass it through
html.unescape, which Django doesn't have a built-in filter for,
probably for good reason. :)  But you could do this:

    def citation_text_plain(self):
        citations = {}
        for style, html_text in self.citation_text_all().items():
            citations[style] = unescape(strip_tags(html_text))
        return citations

Or, maybe we just ought to define a custom "convert-to-plain-text"
template filter.

**Comment by tompollard** [comment]
Thanks @bemoody. 

> Do you have a particular reason for using the Vancouver style? 

Not especially, other than it is the one that I'm most familiar with. Well spotted on the mismatch with the style that appears elsewhere. I've swapped to APA for consistency. 

> It's also awkward that you're changing the Python API here in order to change the result at the template level.

Having a default style in the function seems like a good idea because it helps to enforce consistency across the site (the alternative is that we state the style in templates, which may lead to mismatches). I've removed the default for now though.

> Simply using striptags will break apostrophes (as well as & " < > if those were allowed.) ... maybe we just ought to define a custom "convert-to-plain-text" template filter.

Good idea. I defined an html-to-text template filter as suggested.

**Comment by bemoody** [comment]
Looks good, thanks!

**Comment by bemoody** [comment]
One small style fix :)

**Comment by tompollard** [comment]
> One small style fix :)

thanks, good catch!

**Pull request merged**
