### PR TITLE
Fix bug in StaticPage 

### PR DESCRIPTION
**Pull request by superryeti**
## Context
Previously, when a StaticPage instance was deleted, the nav_order values of the remaining instances were not properly adjusted, leading to gaps or duplicates in the nav_order sequence. This caused issues when trying to move the remaining instances up or down in the sequence. Similarly, on static page edit, we were increasing the nav_order on every edit, which leads to the same error as described above.

To fix this issue, i overode the delete method of the StaticPage model to properly update the nav_order values of remaining instances when an instance is deleted. This change ensures that the nav_order sequence remains valid and consistent even after instances are deleted. Similarly, i also fixed the save method in StaticPage form.

### Method 1:
1. Edit any static page which is not on the bottom of the list(maybe edit the top static page or the one in the middle)
2. Notice that you will see 500 error which will complain about duplicate nav_order

### Method2:
1. Go to the admin panel 
2. Delete the static page with nav_order = 2 from the list. This will leave a gap in the nav_order sequence: 1, 3, 4.
3. Try to move the static page with nav_order = 4 up in the order by clicking on the “Up Arrow” button next to it. This will cause an IntegrityError, because it will try to update the nav_order of the static page with nav_order = 3 to 4, which is already taken by another static page.

## Question
1. For the already existing nav_orders in database which might have gaps in nav_order and can potentially lead to the integrity error, do we write a migration file to change the order for existing staticpages

Thanks to @january-adams for finding the bug

### CODE REVIEW

**Comment by tompollard** [comment]
Not had a chance to investigate why, but when I tested this branch on a fresh database I hit the following server error regularly. Bit vague (sorry) but I can generate these errors by:

1. Create two or three new static pages
2. Delete a couple of pages
3. Move content up and down

Let me know if you aren't able to reproduce the error and I'll try to add a detailed list of steps.

```
Traceback (most recent call last):
  File "/Users/tompollard/projects/physionet-build/env/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/tompollard/projects/physionet-build/env/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)

The above exception (UNIQUE constraint failed: physionet_staticpage.nav_order) was the direct cause of the following exception:
  File "/Users/tompollard/projects/physionet-build/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/Users/tompollard/projects/physionet-build/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/tompollard/projects/physionet-build/env/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/tompollard/projects/physionet-build/physionet-django/console/views.py", line 2540, in static_pages
    page.move_up()
  File "/Users/tompollard/projects/physionet-build/physionet-django/physionet/models.py", line 31, in move_up
    StaticPage.objects.filter(nav_order=nav_order - 1).update(nav_order=nav_order)
  File "/Users/tompollard/projects/physionet-build/env/lib/python3.10/site-packages/django/db/models/query.py", line 1191, in update
    rows = query.get_compiler(self.db).execute_sql(CURSOR)
  File "/Users/tompollard/projects/physionet-build/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/Users/tompollard/projects/physionet-build/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1398, in execute_sql
    cursor.execute(sql, params)
  File "/Users/tompollard/projects/physionet-build/env/lib/python3.10/site-packages/debug_toolbar/panels/sql/tracking.py", line 205, in execute
    return self._record(self.cursor.execute, sql, params)
  File "/Users/tompollard/projects/physionet-build/env/lib/python3.10/site-packages/debug_toolbar/panels/sql/tracking.py", line 140, in _record
    return method(sql, params)
  File "/Users/tompollard/projects/physionet-build/env/lib/python3.10/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/Users/tompollard/projects/physionet-build/env/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/Users/tompollard/projects/physionet-build/env/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/tompollard/projects/physionet-build/env/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/Users/tompollard/projects/physionet-build/env/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/tompollard/projects/physionet-build/env/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/tompollard/projects/physionet-build/env/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)

Exception Type: IntegrityError at /console/static-pages/
Exception Value: UNIQUE constraint failed: physionet_staticpage.nav_order
```

**Comment by superryeti** [comment]
Thanks @tompollard . Thats weird, I was trying to fix that error. let me take a look.

**Comment by superryeti** [comment]
@tompollard i couldnot reproduce the bug with move up and down, but i found the integrity error when i tried the same steps like you mentioned with delete action. Weirdly i cant reproduce the bug consistently but it appeared sometimes when i start with fresh database.

I also updated the code to make sure the deletion doesnot mess up the nav_order and happens gracefully.

I tested bunch of times after the current commit and cant see the error anymore.

Could you check once if you are getting the errror with move_up/down(i didnot get the error with move_up/down for some reason)

**Comment by tompollard** [comment]
Looks good to me, thanks Amit

**Pull request merged**
