### PR TITLE
Main page style fixes

### PR DESCRIPTION
**Pull request by bemoody**
Fix some of the bad word breaking currently going on on the main page
(eICU Collaborativ e Research Database, Visceral adipose tissue
measureme nts during pregnancy).  And fix the logical header structure.

### CODE REVIEW

**Comment by tompollard** [comment]
Thanks, this looks useful. I don't see the awkward breaks that you've mentioned above. Please could you share a screenshot just for interest?

**Comment by bemoody** [comment]
Here's a screenshot.  I don't know why it doesn't show the background image at the top.

**Comment by bemoody** [comment]
okay, so I guess "attach files" does nothing

https://archive.physionet.org/users/shared/benjamin/screenshot20200408.png

**Comment by tompollard** [comment]
thanks, looks good to me.

**Pull request merged**
