### PR TITLE
Minor changes to the console and admin pages

### PR DESCRIPTION
**Pull request by tompollard**
This pull request introduces some minor changes to the console and admin pages. The main ones are:

- Remove icons from the headers of admin pages because they interfere with readability.
- Move projects to a submenu for consistency with the other menu items.
- Removes explanatory text from the sections in /console/editor-home/ based on feedback by Felipe. The headers are clear and we can add explanatory text later if requested.

### CODE REVIEW

**Comment by elfeto** [comment]
- The icons should stay at the left and not the right.
- Why is users and news (like the current) a drop down, if there is only one thing there.
- Why is there a add news sub menu, News should be its own thing (not drop down), and should be ok with just the add news button

**Comment by tompollard** [comment]
Thanks for taking a look!

> The icons should stay at the left and not the right.

At the moment they affect readability because the left alignment of the text isn't consistent. I'll take another look to see if I can find a happy alternative (either make fixed width on left or better, just remove them while the bar is open).

> Why is users and news (like the current) a drop down, if there is only one thing there.

I agree it's inconsistent, but this is current functionality. I think Chen probably anticipated more items appearing in these menus in future.

> Why is there a add news sub menu, News should be its own thing (not drop down), and should be ok with just the add news button

This is the current functionality. I agree the "add items" section seems unnecessary, and if it was removed then the menu could be collapsed. If Chen has no objections, I can add a change to this pull request.

**Comment by tompollard** [comment]
The news menu is now collapsed. Looks like the base theme is at: https://startbootstrap.com/themes/sb-admin-2/

**Comment by tompollard** [comment]
Perfect, thanks. Fixes #240. Okay to merge?

**Pull request merged**
