### PR TITLE
Displays debug toolbar when in development mode #1156

### LINKED ISSUE #1156: Display profiler console when in the development environment
[development/base.py](https://github.com/MIT-LCP/physionet-build/blob/dev/physionet-django/physionet/settings/development/base.py) includes a reference to a debug toolbar (`MIDDLEWARE += ['debug_toolbar.middleware.DebugToolbarMiddleware', ]`). 

We should update the dev environment to display the toolbar, unless anyone can see a reason not to do so.

It looks like displaying the toolbar requires the following chunk to be added to [base.py](https://github.com/MIT-LCP/physionet-build/blob/dev/physionet-django/physionet/settings/development/base.py):

```
INTERNAL_IPS = [
    '127.0.0.1',
]
```

...and [urls.py ](https://github.com/MIT-LCP/physionet-build/blob/dev/physionet-django/physionet/urls.py) needs to reference the toolbar URL:

```
import debug_toolbar

urlpatterns = [
    # ...
    path('__debug__/', include(debug_toolbar.urls)),
    # ...
```

Once this is done, the toolbar should appear:

Screen Shot 2020-11-10 at 13 26 22

### PR DESCRIPTION
**Pull request by Lucas-Mc**
This change displays the debug toolbar when in development mode. Metrics displayed here include things such as SQL queries, number of static files, CPU time, etc.

Fixes #1156.

### CODE REVIEW

**Comment by bemoody** [comment]
Thanks, Lucas.

I am a little concerned that the staging configuration
(physionet/settings/staging.py) enables the debug flag.  Probably that
should be turned off for safety, *even if* debug features are only
accessible to localhost (which I haven't checked.)

But having this enabled for development will be really useful!

**Comment by Lucas-Mc** [comment]
Thanks Benjamin! That's true, what do we currently use the `DEBUG` flag for on staging? If we do turn off that flag, we should be sure that it doesn't hinder anything like detailed stack traces for errors.

**Comment by tompollard** [comment]
We should also avoid the import and URL pattern unless needed. If we only want this on systems with DEBUG=TRUE, then see: https://django-debug-toolbar.readthedocs.io/en/1.0/installation.html

```
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )
```

**Comment by Lucas-Mc** [comment]
Thanks @tompollard, I moved the URL import into a conditional based on the debug settings.

**Comment by tompollard** [comment]
Thanks Lucas, this looks good to me. 

Do you want to set the debug flag to false on staging too, as suggested by @bemoody? https://github.com/MIT-LCP/physionet-build/blob/dev/physionet-django/physionet/settings/staging.py

It's easy enough to temporarily switch the flag to true on staging when necessary for debugging. In most cases, I think we only really need debug=true when on dev.

**Comment by Lucas-Mc** [comment]
Thanks for the clarification Tom! I was just waiting to see if changing the `DEBUG` flag would affect anything on staging but since not I can switch now.

**Comment by elfeto** [comment]
I was reading a bit on this (debug toolbar)
There are several things needed for this to work, as stated here:
https://django-debug-toolbar.readthedocs.io/en/latest/installation.html

>  MIDDLEWARE += ['debug_toolbar.middleware.DebugToolbarMiddleware', ]

>import debug_toolbar
urlpatterns = [
    ...
    path('__debug__/', include(debug_toolbar.urls)),
]

>INTERNAL_IPS = [
    # ...
    '127.0.0.1',
    # ...
]

and obviously, `DEBUG=True`
Without these things, it wont work... 

The only place the `DebugToolbarMiddleware` and `INTERNAL_IPS` are set in  `physionet/settings/development/base.py` not in staging.
Even if the URL is added it wont work without that.

I would say its safe to assume that the DEBUG can stay in staging, BUT we might want to make staging as close to prod as possible removing the DEBUG option.

**Comment by tompollard** [comment]
Thanks Felipe -

> ... we might want to make staging as close to prod as possible removing the DEBUG option.

Nice point, this makes a good case for switching off DEBUG on staging.

**Comment by bemoody** [comment]
> Nice point, this makes a good case for switching off DEBUG on staging.

Yeah, I think that's probably a good idea, but could be done
independently of this pull request.  I'm happy either way.

**Pull request merged**
