### PR TITLE
Parsing legacy content

### PR DESCRIPTION
**Pull request by lbulgarelli**
Here's a try at parsing the legacy project's into the project sections structure #602.

- Function `parse_legacy_content` searches for `<h>` tags as basis to create sections
- Migration applies function to all legacy projects
- Templates now have almost the same behavior for legacy and non-legacy projects, except that legacy projects don't actually have an abstract.

For now, I'm keeping the `LegacyProject` model there. If there's a consent that it could already be removed then I can do that as well.

### CODE REVIEW

**Comment by elfeto** [comment]
so... testing this out is a bit unorthodox....

The text data for the legacy exists on a unloaded fixture...

Hopefully to reproduce this... you go to `projectsections`, and do the following commands
```
./manage.py resetdb
./manage.py loaddemo
./manage.py loaddata pbank

./manage.py shell

from project.models import LegacyProject, ActiveProject, PublishedProject, ProjectSection
l = LegacyProject.objects.all()
for item in l: item.publish()
```
That should publish all the legacy project's text information.

You will be able to see them like this: http://localhost:8000/content/demobsn/1.0/

Then I did a parse legacy:

```
q = PublishedProject.objects.get(slug='ecgcipa')
q. parse_legacy_content()
```

That gives me a field error:
```
FieldError at /content/ecgcipa/1.0.0/
Cannot resolve keyword 'custom_order' into field. Choices are: id, project, project_id, project_section, project_section_id, section_content
```

This is the LONG traceback
```
Template error:
In template /Users/ftorres/Github/physionet-build/physionet-django/templates/base.html, error at line 0
   Cannot resolve keyword 'custom_order' into field. Choices are: id, project, project_id, project_section, project_section_id, section_content
   1 : &lt;!DOCTYPE html&gt;
   2 : {% load static %}
   3 : &lt;html lang=&quot;en&quot;&gt;
   4 :   &lt;head&gt;
   5 :     &lt;meta charset=&quot;UTF-8&quot;&gt;
   6 :     &lt;title&gt;{% block title %}{% endblock %}&lt;/title&gt;
   7 :     {% block meta %}{% endblock %}
   8 :     {% include &quot;base_css.html&quot; %}
   9 :     {% block local_css %}{% endblock %}
   10 :     {% include &quot;base_js_top.html&quot; %}


Traceback:

File "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/core/handlers/base.py" in _get_response
  115.                 response = self.process_exception_by_middleware(e, request)

File "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/core/handlers/base.py" in _get_response
  113.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/Users/ftorres/Github/physionet-build/physionet-django/project/views.py" in published_project
  1557.                   status=status)

File "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/shortcuts.py" in render
  36.     content = loader.render_to_string(template_name, context, request, using=using)

File "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/template/loader.py" in render_to_string
  62.     return template.render(context, request)

File "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/template/backends/django.py" in render
  61.             return self.template.render(context)

File "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/template/base.py" in render
  171.                     return self._render(context)

File "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/test/utils.py" in instrumented_test_render
  96.     return self.nodelist.render(context)

File "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/template/base.py" in render
  937.                 bit = node.render_annotated(context)

File "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/template/base.py" in render_annotated
  904.             return self.render(context)

File "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/template/loader_tags.py" in render
  150.             return compiled_parent._render(context)

File "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/test/utils.py" in instrumented_test_render
  96.     return self.nodelist.render(context)

File "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/template/base.py" in render
  937.                 bit = node.render_annotated(context)

File "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/template/base.py" in render_annotated
  904.             return self.render(context)

File "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/template/loader_tags.py" in render
  62.                 result = block.nodelist.render(context)

File "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/template/base.py" in render
  937.                 bit = node.render_annotated(context)

File "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/template/base.py" in render_annotated
  904.             return self.render(context)

File "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/template/loader_tags.py" in render
  62.                 result = block.nodelist.render(context)

File "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/template/base.py" in render
  937.                 bit = node.render_annotated(context)

File "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/template/base.py" in render_annotated
  904.             return self.render(context)

File "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/template/defaulttags.py" in render
  166.             len_values = len(values)

File "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/db/models/query.py" in __len__
  256.         self._fetch_all()

File "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/db/models/query.py" in _fetch_all
  1242.             self._result_cache = list(self._iterable_class(self))

File "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/db/models/query.py" in __iter__
  55.         results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)

File "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/db/models/sql/compiler.py" in execute_sql
  1120.             sql, params = self.as_sql()

File "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/db/models/sql/compiler.py" in as_sql
  474.             extra_select, order_by, group_by = self.pre_sql_setup()

File "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/db/models/sql/compiler.py" in pre_sql_setup
  55.         order_by = self.get_order_by()

File "/Users/ftorres/Github/physionet-build/physionet-django/physionet/db/chaotic/compiler.py" in get_order_by
  22.         result = super().get_order_by()

File "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/db/models/sql/compiler.py" in get_order_by
  330.                     field, self.query.get_meta(), default_order=asc))

File "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/db/models/sql/compiler.py" in find_ordering_name
  704.         field, targets, alias, joins, path, opts, transform_function = self._setup_joins(pieces, opts, alias)

File "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/db/models/sql/compiler.py" in _setup_joins
  734.         field, targets, opts, joins, path, transform_function = self.query.setup_joins(pieces, opts, alias)

File "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/db/models/sql/query.py" in setup_joins
  1504.                     names[:pivot], opts, allow_many, fail_on_missing=True,

File "/Users/ftorres/Github/physionet-build/env/lib/python3.7/site-packages/django/db/models/sql/query.py" in names_to_path
  1420.                                      "Choices are: %s" % (name, ", ".join(available)))
```

**Comment by tompollard** [comment]
@elfeto I'm not able to reproduce your error. Trying to work out why...

**Comment by elfeto** [comment]
@tompollard  Maybe it was the way I was doing the testing (wrong?). I don't get the error now, and it parses the legacy content into the DB correctly for what I can tell.

some minor details.

> from bs4 import Comment
from bs4 import BeautifulSoup

can be merged as one `from bs4 import Comment, BeautifulSoup`

**bs4 is not in the requirements.txt file**

apart from that, I think is fine.

**Comment by elfeto** [comment]
Also, not related to this PR but it's broken about the legacy.

The `resource_type` in the publish function has changed in X PR that I cant recall right now, and its no longer a number.
>\-            resource_type=self.resource_type,
\+            resource_type=ProjectType.objects.get(id=self.resource_type),

**Comment by tompollard** [comment]
Overall, this looks good to me. I think it will be easier to do a detailed review when it appears alongside the rest of the changes in https://github.com/MIT-LCP/physionet-build/pull/602.

**Pull request merged**
