### PR TITLE
Adds explanatory text to remove button #925

### PR DESCRIPTION
**Pull request by Lucas-Mc**
Adds a simple question mark next to the remove button which, upon hover, reveals an explanation as to what the exact functionality of the remove button is.

### CODE REVIEW

**Comment by tompollard** [comment]
Not tested, but sounds like this might be overkill. The other sections show text in `<p>` `</p>`. Is there a good reason to do this differently?

**Comment by Lucas-Mc** [comment]
@tompollard  I just figured if someone had a question regarding the remove button then it should be placed right there so they don't have to dig for it. Where do you think it should go? Maybe right above the table?

**Comment by tompollard** [comment]
@Lucas-Mc  My original thought was that we would add a bit more detail where it says "Add and remove storage options." (should have made it clearer in the issue, sorry!). If we want to add location/service specific details, then these could go into a new column perhaps?

**Comment by tompollard** [comment]
thanks, looks good to me

**Pull request merged**
