### PR TITLE
Auto save ckeditor forms to help prevent loss of user created content #1279

### PR DESCRIPTION
**Pull request by tompollard**
As discussed in #1279, form data is only saved when the user clicks the "save" button. Users can easily lose content that they have created if they navigate away from the page without saving.

This pull request adds "autosave" functionality to the ckeditor form fields. These fields tend to contain large passages of text, so are some of the most important fields to protect. 

The functionality is described below:

1. the page autosaves every ~20 seconds (and a small "autosaved" message is displayed).
2. when returning to an unsaved page, the following message is displayed:

Screen Shot 2021-03-03 at 14 47 17

3. the user can check and accept/reject a diff of the changes.

Screen Shot 2021-03-03 at 14 52 20

### CODE REVIEW

**Comment by bemoody** [comment]
Interesting, so to be clear, we're talking about auto saving on the
*client* side; it gets put in localStorage or something.

I haven't tested it but it seems like this interface might be somewhat
confusing (especially if you closed the window, went off and edited
the project on another machine, then later came back to the first
machine.)  But I don't have a horse in this race and any improvement
here is probably better than nothing.

I assume it's smart enough to associate the autosaved content with a
particular project (form URL) and a particular form field?  And I
assume it's also smart enough to *delete* the autosaved content once
the form is successfully submitted?

**Comment by tompollard** [comment]
> Interesting, so to be clear, we're talking about auto saving on the *client* side; it gets put in localStorage or something.

That's right, a file is saved in the client's local storage (screenshot below from Google Chrome inspector).

Screen Shot 2021-03-03 at 18 20 04

The key is based on the URL and the form ID (e.g.: `autosave_http://localhost:8000/projects/OTeYYnJlM6DCKMxl87QA/content/_id_abstract`) and the value contains the encoded text.

> I haven't tested it but it seems like this interface might be somewhat confusing (especially if you closed the window, went off and edited the project on another machine, then later came back to the first machine.)

I agree, it could be a little for confusing for someone working in multiple locations. There is a time out that can be set on the autosave (default is 24 hours) which may help. 

I tried simulating this use case by working in multiple browsers, and I don't think it is a huge problem. The interface does a fairly good job at explaining what is happening (i.e. you have a temporary version that doesn't match the current version. do you want to look at the differences?).

> I assume it's smart enough to associate the autosaved content with a
particular project (form URL) and a particular form field?  

Yes, each field is identified by URL + form ID.

> And I assume it's also smart enough to *delete* the autosaved content once
the form is successfully submitted?

Yes, the client-side files are deleted when the page is saved.

> But I don't have a horse in this race and any improvement here is probably better than nothing.

If you and/or @alistairewj would prefer to just warn users when leaving the page, then I'm happy to go for that instead. In this case, ideally the user would only be warned if they have unsaved changes (not sure from the top of my head how that would be done). 

One benefit of autosave plugin approach is that it is pretty straightforward to undo if people don't like it. To undo, we just need to remove the "autosave" item from the config (and ideally delete the plugin content).

**Comment by alistairewj** [comment]
I think I prefer the auto-save over a "warning, you are going to leave" dialog box. It's more likely to be effective since everyone has been hard-wired to ignore pop-up dialog boxes warning you about stuff. Feature looks nice!

**Comment by bemoody** [comment]
After testing this, I do have concerns about the UI.  The fact that it
(briefly) says "Auto Saved" will make people think that the page was,
in fact, *saved* and they don't need to click the submit button.

It appears this message can be suppressed by setting:

    'autosave': {'messageType': 'no'},

**Comment by tompollard** [comment]
That's a good point. Would you be happy using the plugin if we suppress the message? (thanks for finding the config for this)

**Comment by tompollard** [comment]
Another minor issue that I didn't notice previously is that the "An autosaved version of this content has been found" popup is displayed once for each form that has been saved, which is a little confusing. It would be good to work out how to display the pop up only once for the page (preferably in a later pull request!).

**Comment by bemoody** [comment]
Yeah, doesn't look like there's an easy way to fix that.

We also need to include the license for the package
(https://github.com/w8tcha/CKEditor-AutoSave-Plugin/blob/master/LICENSE.md),
and while you're at it, please include the original .css and .js
source files that the .min.css and .min.js files were generated
from
(https://github.com/w8tcha/CKEditor-AutoSave-Plugin/tree/master/autosave/css,
https://github.com/w8tcha/CKEditor-AutoSave-Plugin/tree/master/autosave/js).

Other than that this looks okay; hopefully it will be helpful and it's
easy to remove later if we find problems.

**Comment by tompollard** [comment]
Thanks Benjamin, the license and source (js/css) files have been added.

**Comment by bemoody** [comment]
Thanks!

**Pull request merged**
