### PR TITLE
Database index updates

### PR DESCRIPTION
**Pull request by bemoody**
Add various recently-published databases to /about/database/, and
a little bit of reorganization and style cleanup.

### CODE REVIEW

**Comment by tompollard** [comment]
Thanks, looks good from a quick review. Before I merge, what is the `*` that appears before some database titles? e.g.:

```py
<li>[Class 3] *<a href="{% url 'published_project_latest' 'picdb' %}">
Paediatric Intensive Care Database</a>.
```

**Comment by bemoody** [comment]
The stars were meant to indicate credentialing required, but I agree
that isn't clear.  I think there was a footnote that got lost
somewhere along the way.  Should we get rid of them or should we add
some text to clarify?

**Comment by tompollard** [comment]
Oh okay, that makes sense. Perhaps we remove for now, and then come up with a clearer way of indicating permissions/licenses later? e.g. we could display each entry in a similar style to https://physionet.org/content/ (but more compact).

**Comment by bemoody** [comment]
I thought about trying to replace these, and the "[Class 1]" - "[Class
3]" labels, with little color-coded icons, but I wasn't really happy
with how it looked.  I'm just going to remove the stars for now.

**Pull request merged**
