### PR TITLE
Remove unused function for getting the training_report_path

### PR DESCRIPTION
**Pull request by tompollard**
While consolidating the paths for training reports on our server, I noticed a redundant function:

```
def training_report_path(instance, filename):
    """
    Storage path of CITI training report
    """
    return 'credential-applications/{}/{}'.format(instance.slug, 'training-report.pdf')
```

As far as I can see, this function isn't used. Instead, we now use:

```
def get_training_path(instance, filename):
    """
    Storage path for training reports relative to media root.
    """
    return f'training/{instance.slug}/training-report.pdf'
```

Side note, is that `get_training_path` asks for filename, but doesn't use it anywhere. This might be a bug? Shouldn't `get_training_path` specify the type of training in the filename? Otherwise I think training reports will be overwritten if there are multiple types @alistairewj @kshalot.

### CODE REVIEW

**Comment by tompollard** [comment]
hmm, do we have to keep it because it appears in the migrations? @bemoody

**Comment by kshalot** [comment]
### Unused `training_report_path` function
My hunch is that this function was simply renamed to `get_training_path` but the old name was kept for the sake of old migrations (which you mentioned). Honestly it looks like you could just remove that function and change it's invocations to `get_training_path` in the migrations.

### Unused `filename` parameter
The parameter is actually necessary because it's part of the FileField "contract". You can see it described here - https://docs.djangoproject.com/en/2.2/ref/models/fields/#django.db.models.FileField.upload_to. The function's arity has to be 2.

This actually shouldn't introduce any conflict since the report is created under a directory denoted by the training's slug - the slug is unique for each training (training == training completion by a user, not a specific training type).

**Comment by tompollard** [comment]
thanks for your helpful comments @kshalot

**Comment by tompollard** [comment]
@bemoody please could you take a look at this when you have a chance?

**Comment by bemoody** [comment]
It looks reasonable and tests are passing.  I haven't really followed
this transition, other than I remember some things were failing when
Karol or somebody tried to write a migration to move the files
automatically.

At this point, have all the files been moved
into '/data/pn-media/training/' on the live server?  Presumably we want
to do the same thing in 'demo-files/media'.

**Comment by bemoody** [comment]
> Side note, is that get_training_path asks for filename, but doesn't use it anywhere. This might be a bug?

I could be completely wrong, but I would guess that the filename argument here is the filename provided by the web browser.  We probably want to ignore that.

**Comment by tompollard** [comment]
> At this point, have all the files been moved into '/data/pn-media/training/' on the live server?

Yes, all the files should be in the new location (see: https://github.com/MIT-LCP/physionet-build/issues/1533).

> Presumably we want to do the same thing in 'demo-files/media'.

I hadn't thought about this, but sounds like a good idea. Can we raise this as an issue and do it later or would you like it addressed in this PR?

**Comment by tompollard** [comment]
> I could be completely wrong, but I would guess that the filename argument here is the filename provided by the web browser. We probably want to ignore that.

Sorry, missed this. See Karol's response to this point above (copied below):

> Unused filename parameter
The parameter is actually necessary because it's part of the FileField "contract". You can see it described here - https://docs.djangoproject.com/en/2.2/ref/models/fields/#django.db.models.FileField.upload_to. The function's arity has to be 2.

> This actually shouldn't introduce any conflict since the report is created under a directory denoted by the training's slug - the slug is unique for each training (training == training completion by a user, not a specific training type).

**Comment by bemoody** [comment]
> I hadn't thought about this, but sounds like a good idea. Can we raise this as an issue and do it later or would you like it addressed in this PR?
Let's do it separately (see: issue #1561).

**Comment by tompollard** [comment]
(@bemoody confirmed that he's happy to merge)

**Comment by bemoody** [comment]
It looks reasonable and tests are passing.  I haven't really followed
this transition, other than I remember some things were failing when
Karol or somebody tried to write a migration to move the files
automatically.

At this point, have all the files been moved
into '/data/pn-media/training/' on the live server?  Presumably we want
to do the same thing in 'demo-files/media'.

**Pull request merged**
