### PR TITLE
Debranding text change in editor workflow and forms

### PR DESCRIPTION
**Pull request by adrianryt**
@alistairewj found some more places that were missed during the initial rebranding. Additionally, the platform wide citation is also PhysioNet-specific - we made it configurable through envvars, with the option to completely disable it (as HDN will not include a platform wide citation at launch). By default, all the new settings are set to show exactly what was configured until now so this PR should not require any changes on your production environment.

#### SHOW_PLATFORM_WIDE_CITATION=False
SHOW PLATFORM_WIDE_CITATION False

#### SHOW_PLATFORM_WIDE_CITATION=True
SHOW_PLATFORM_WIDE_CITATION True

### CODE REVIEW

**Comment by tompollard** [comment]
Thanks @adrianryt. It would be great if the platform citation could be included in the config file itself, rather than a True/False flag that calls the hardcoded citation. Can you see a quick way of implementing this? 

I guess the challenge is handling multiple formats? If the citation was provided as structured data (e.g. BIB file or python dictionary), perhaps this would help? We can save this improvement for later if necessary.

**Comment by adrianryt** [comment]
@tompollard thanks for comment. 

> It would be great if the platform citation could be included in the config file itself

Right now platform citation isn't hardcoded but configurable by env file (just default value is given), so I kinda don't understand this part.

In this implementation each format has separate env and I think it's a good idea to make it dictionary. basy.py would look like this.

```
PLATFORM_WIDE_CITATION = {
            'MLA': config('PLATFORM_WIDE_CITATION_MLA', default='Goldberger, A., et al. "PhysioBank, '
                    'PhysioToolkit, and PhysioNet: Components of a '
                    'new research resource for complex physiologic '
                    'signals. Circulation [Online]. 101 (23), pp. '
                    'e215–e220." (2000).')
            'APA': config('PLATFORM_WIDE_CITATION_APA', default='Goldberger, A., Amaral, L., Glass, L., '
                    'Hausdorff, J., Ivanov, P. C., Mark, R., ... & '
                    'Stanley, H. E. (2000). PhysioBank, '
                    'PhysioToolkit, and PhysioNet: Components of a '
                    'new research resource for complex physiologic '
                    'signals. Circulation [Online]. 101 (23), pp. '
                    'e215–e220.')
            ...
        }
```

**Comment by bemoody** [comment]
I think it'd be cleaner not to define default values for any of these
(PLATFORM_WIDE_CITATION_MLA, PLATFORM_WIDE_CITATION_APA, etc.) and
don't show the citation if these variables are undefined.

There shouldn't be a need for an additional template parameter
SHOW_PLATFORM_WIDE_CITATION; rather, Metadata.get_platform_citation()
should return None (or an empty dictionary) if there is no platform
citation defined.

**Comment by adrianryt** [comment]
@tompollard quick fix from me. I removed SHOW_PLATFORM_WIDE_CITATION, also PLATFORM_WIDE_CITATION is now python dictionary.

**Comment by bemoody** [comment]
This looks good.  Would you please add these new variables
to .env.example?  Something like this:

    # Citation for the platform (in various common styles.)
    # If set, this will be included among the "recommended citations"
    # at the top of each published project page.
    #PLATFORM_WIDE_CITATION_APA=
    #PLATFORM_WIDE_CITATION_MLA=
    #PLATFORM_WIDE_CITATION_CHICAGO=
    #PLATFORM_WIDE_CITATION_HARVARD=
    #PLATFORM_WIDE_CITATION_VANCOUVER=

You can add some dummy text if you like or just leave the variables
commented-out.

**Comment by adrianryt** [comment]
@bemoody Done

**Comment by tompollard** [comment]
@adrianryt there seem to be a couple of conflicts that need to be resolved (`.env.example`; `physionet-django/physionet/settings/base.py`). please could you take a look?

**Comment by tompollard** [comment]
This looks good to me.  One minor issue is that it's a little unclear what exactly `main_platform_citation` will display (i.e. which format is used for the default citation that's displayed at the top of the page). The following chunk:

```
main_platform_citation = next((item for item in platform_citations.values() if item is not None), '')
```

....looks like it will get the first populated value from the `PLATFORM_WIDE_CITATION` dictionary below:

```
PLATFORM_WIDE_CITATION = {
    'APA': config('PLATFORM_WIDE_CITATION_APA', default=None),
    'MLA': config('PLATFORM_WIDE_CITATION_MLA', default=None),
    'CHICAGO': config('PLATFORM_WIDE_CITATION_CHICAGO', default=None),
    'HARVARD': config('PLATFORM_WIDE_CITATION_HARVARD', default=None),
    'VANCOUVER': config('PLATFORM_WIDE_CITATION_VANCOUVER', default=None),
}
```

There are a couple of minor issues with this approach:
1. the behavior is going to be a bit mysterious for people who aren't familiar with the code.
2. it isn't especially flexible. e.g. how would someone use Vancouver as their main style, while also offering the others as alternatives?
3. Pre-Python 3.7ish I don't think dictionaries are ordered (meaning `next` could return an unpredictable style).

**Comment by tompollard** [comment]
This looks good to me.  One minor issue is that it's a little unclear what exactly `main_platform_citation` will display (i.e. which format is used for the default citation that's displayed at the top of the page). The following chunk:

```
main_platform_citation = next((item for item in platform_citations.values() if item is not None), '')
```

....looks like it will get the first populated value from the `PLATFORM_WIDE_CITATION` dictionary below:

```
PLATFORM_WIDE_CITATION = {
    'APA': config('PLATFORM_WIDE_CITATION_APA', default=None),
    'MLA': config('PLATFORM_WIDE_CITATION_MLA', default=None),
    'CHICAGO': config('PLATFORM_WIDE_CITATION_CHICAGO', default=None),
    'HARVARD': config('PLATFORM_WIDE_CITATION_HARVARD', default=None),
    'VANCOUVER': config('PLATFORM_WIDE_CITATION_VANCOUVER', default=None),
}
```

There are a couple of minor issues with this approach:
1. the behavior is going to be a bit mysterious for people who aren't familiar with the code.
2. it isn't especially flexible. e.g. how would someone use Vancouver as their main style, while also offering the others as alternatives?
3. Pre-Python 3.7ish I don't think dictionaries are ordered (meaning `next` could return an unpredictable style).

**Comment by tompollard** [comment]
I'm going to merge this, because overall I think it's an improvement. We can look into the points above another time.

**Comment by tompollard** [comment]
@bemoody @danamouk @briangow new text for your .env file!:

```
# Citation for the platform (in various common styles.)
# If set, this will be included among the "recommended citations"
# at the top of each published project page.
PLATFORM_WIDE_CITATION_APA='Goldberger, A., Amaral, L., Glass, L., Hausdorff, J., Ivanov, P. C., Mark, R., ... & Stanley, H. E. (2000). PhysioBank, PhysioToolkit, and PhysioNet: Components of a new research resource for complex physiologic signals. Circulation [Online]. 101 (23), pp. e215–e220.'
PLATFORM_WIDE_CITATION_MLA='Goldberger, A., et al. "PhysioBank, PhysioToolkit, and PhysioNet: Components of a new research resource for complex physiologic signals. Circulation [Online]. 101 (23), pp. e215–e220." (2000).'
PLATFORM_WIDE_CITATION_CHICAGO='Goldberger, A., L. Amaral, L. Glass, J. Hausdorff, P. C. Ivanov, R. Mark, J. E. Mietus, G. B. Moody, C. K. Peng, and H. E. Stanley. "PhysioBank, PhysioToolkit, and PhysioNet: Components of a new research resource for complex physiologic signals. Circulation [Online]. 101 (23), pp. e215–e220." (2000).'
PLATFORM_WIDE_CITATION_HARVARD='Goldberger, A., Amaral, L., Glass, L., Hausdorff, J., Ivanov, P.C., Mark, R., Mietus, J.E., Moody, G.B., Peng, C.K. and Stanley, H.E., 2000. PhysioBank, PhysioToolkit, and PhysioNet: Components of a new research resource for complex physiologic signals. Circulation [Online]. 101 (23), pp. e215–e220.'
PLATFORM_WIDE_CITATION_VANCOUVER='Goldberger A, Amaral L, Glass L, Hausdorff J, Ivanov PC, Mark R, Mietus JE, Moody GB, Peng CK, Stanley HE. PhysioBank, PhysioToolkit, and PhysioNet: Components of a new research resource for complex physiologic signals. Circulation [Online]. 101 (23), pp. e215–e220.'
```

**Pull request merged**
