### PR TITLE
Replace `NullBooleanField` with `BooleanField(null=True)`

### PR DESCRIPTION
**Pull request by tompollard**
`NullBooleanField` is deprecated in version 3.0 of Django (ref https://github.com/MIT-LCP/physionet-build/issues/1095). See: https://code.djangoproject.com/ticket/31369. In preparation for this deprecation, `BooleanField` was updated to support a `null=True` argument. 

This pull request switches to the new syntax (i.e. from `NullBooleanField` with `BooleanField(null=True)`). Note that most (or all?) of the fields that are being updated could potentially be removed altogether (see: https://github.com/MIT-LCP/physionet-build/issues/1571).

### CODE REVIEW

**Comment by tompollard** [comment]
(I didn't intend to include 4ff240aee607f550024c6691b2b7b70e1a5efec9 but it wouldn't hurt to merge that too!).

**Comment by briangow** [comment]
@tompollard , in addition to the old migration files I see a couple of other files which still use `NullBooleanField`:

physionet-django/project/modelcomponents/submission.py
physionet-django/project/modelcomponents/generic.py

**Comment by tompollard** [comment]
@briangow thanks for picking that up. looks like i broke something in the update...looking into it!

**Comment by tompollard** [comment]
Not investigated, but I \*think\* the failing tests are a result of the (hacky) way some of the review response choices are coded:

https://github.com/MIT-LCP/physionet-build/blob/dceccf0e44fbb0b527800dc00130929b2b5bc6bd/physionet-django/console/forms.py#L48-L65

```
======================================================================
FAIL: test_edit (console.test_views.TestState)
Edit a project. Request resubmission, then accept.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/physionet-build/physionet-build/physionet-django/console/test_views.py", line 116, in test_edit
    self.assertTrue(project.author_editable())
AssertionError: None is not true

======================================================================
FAIL: test_edit_reject (console.test_views.TestState)
Edit a project, rejecting it.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/physionet-build/physionet-build/physionet-django/console/test_views.py", line 96, in test_edit_reject
    self.assertTrue(ArchivedProject.objects.filter(slug=project.slug))
AssertionError: <QuerySet []> is not true
```

**Comment by tompollard** [comment]
I think this is now good to merge. The issue is that the `YES_NO_UNDETERMINED` choice requires the field to differentiate between `""` and `None`. For now, I've added the `blank=True` flag to the fields using these choices. 

It would be best to update the fields to properly capture the different choices using an enum. I would like to do this in a later step (and will raise an issue for the task if this PR is merged).

**Pull request merged**
