### PR TITLE
account activation with password

### PR DESCRIPTION
**Pull request by elfeto**
I am using the same method Django uses to reset the password but with the account validation.
Apparently the user token should be kept secret. 

Django uses active accounts by default, so they don't have a mechanism to hide the password on account activation.
I am using a similar or same code as in "django/contrib/auth/views.py".

This would hopefully open leeway to use the same or similar functions on adding an email and activating it.

### CODE REVIEW

**Comment by elfeto** [comment]
This should close #883

**Comment by bemoody** [comment]
Thanks!

You use the "readonly" attribute here rather than making the form
field "disabled".  Is that just because it looks better or is
there another reason?

In clean_password2, then, we probably want to use 'self.user',
*not* self.data['username'].

<http://127.0.0.1:8000/activate/NQ/5eh-4740b50ee8574c31ec3d/>
saves the token in a session variable and then redirects to
<http://127.0.0.1:8000/activate/NQ/user-activation/>.  The
redirection is a good idea, but it's a little confusing to reuse
the same view function this way.

The old activate_user function would also check whether
'user.is_active' is already set.  Probably if the token is valid
and the user is already active then this should redirect to the
login form.

Also, the new activation form should include the zxcvbn password
strength bar.

**Comment by elfeto** [comment]
>You use the "readonly" attribute here rather than making the form
field "disabled".  Is that just because it looks better or is
there another reason?
 
No reason, I wanted the "disabled" usage. It was the first thing that came to mind.

>In clean_password2, then, we probably want to use 'self.user',
*not* self.data['username'].

Since its not a modelform it doesn't have a 'self.user', I tried making it a modelform to use that, but even providing the instance it tried to re-create the username and it gave me a duplicate error

>The old activate_user function would also check whether
'user.is_active' is already set.  Probably if the token is valid
and the user is already active then this should redirect to the
login form.

Then I will add a message with this saying that the account is already active (to not confuse the user)

>Also, the new activation form should include the zxcvbn password
strength bar.

I knew something was missing!!! ty :)

**Comment by elfeto** [comment]
I changed:
 - From readonly to disabled
 - To self.user in clean_password2
 - Redirecting if the user is active with a message
 - Added  zxcvbn password strength bar

**Comment by bemoody** [comment]
Hmm.  If you just set the disabled HTML attribute then it complains
the field is missing.  You want to set "disabled=True" as a parameter
for the CharField/EmailField.

activate_user should also use @sensitive_post_parameters so if it
crashes, passwords are not saved in the logs.

**Comment by elfeto** [comment]
Fixed it and activated the account. :)

**Comment by bemoody** [comment]
Tried to test this as many ways as I could think of and it looks good.

**Pull request merged**
